### ISSUE TITLE
Do not download pkg-config by default

### ISSUE THREAD

**Issue by dalcde** [psychon/x11rb#115]
As far as I can tell, `pkg-config` is only used when `vendor-xcb-proto` is disabled. Therefore it should only be a dependency if `vendor-xcb-proto` is disabled.

I'm not sure if Cargo allows this as it currently stands. One might have to redefine the features so that one turns on the feature to *not* use the vendored copy, instead of the other way round.

**Comment by psychon** [comment]
Fixed by removing the `pkg-config` dependency completely in #280.
