### ISSUE TITLE
Use our own type aliases in the generated code

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#135]
Originally suggested by @dalcde in #66. Basically the following function signature:
```rust
pub fn destroy_window<Conn>(conn: &Conn, window: u32) -> Result<VoidCookie<Conn>, ConnectionError>
where Conn: RequestConnection + ?Sized
```
...should instead look like this (the difference is in the type of `window`: `u32` vs `WINDOW`):
```rust
pub fn destroy_window<Conn>(conn: &Conn, window: WINDOW) -> Result<VoidCookie<Conn>, ConnectionError>
where Conn: RequestConnection + ?Sized
```
However, it seems to me that xcbgen does not make the necessary information available to us. Type aliases are handled in a way that do not allow access to the original type name that was queried, only the resolved type.

**Comment by psychon** [comment]
Uhm... Apparently I was wrong and this *is* possible. Somehow.
```
$ grep -A 1 destroy_window_checked /usr/include/xcb/xproto.h
xcb_destroy_window_checked (xcb_connection_t *c,
                            xcb_window_t      window);
```

**Comment by psychon** [comment]
(There is a `field_type` member on fields that I did not see before, that's how this stuff works. Sadly/luckily, this does not work for booleans, so my hack/workaround for that is still necessary.)

**Comment by dalcde** [comment]
Is it possible to do the same for Reply/Error/Event objects?

**Comment by psychon** [comment]
What exactly do you mean?
```rust
pub struct InternAtomReply {
    pub response_type: u8,
    pub sequence: u16,
    pub length: u32,
    pub atom: u32,
}
```
Atom should have type `ATOM` instead of `u32`? From a quick look at the XML, this should be possible somehow.
```xml
    <reply>
      <pad bytes="1" />
      <field type="ATOM" name="atom" altenum="Atom" />
    </reply>
```
And again, libxcb already manages to do this:
```c
typedef struct xcb_intern_atom_reply_t {
    uint8_t    response_type;
    uint8_t    pad0;
    uint16_t   sequence;
    uint32_t   length;
    xcb_atom_t atom;
} xcb_intern_atom_reply_t;
```

**Comment by dalcde** [comment]
Yep.

**Comment by psychon** [comment]
By the way: Thanks for finding and suggesting these things (and also: happy new year)
