### ISSUE TITLE
Make errors nicer

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#14]
The [current situation around error handling](https://github.com/psychon/x11rb/blob/master/src/errors.rs) is.... quite improvable. This should be improved and organised somehow.

Should there be a single, all-encompasing error enum? Multiple smaller ones like currently?

Could also use something like https://github.com/dtolnay/anyhow or https://github.com/dtolnay/thiserror.

**Comment by psychon** [comment]
I ended up adding another kind of error for `RustConnection` server-rejects-the-connection handling (libxcb handles this by just writing the error message directly to stderr...). The new error is not in `src/errors.rs`, so I mention it here explicitly. This will also need some cleanup-ing:
https://github.com/psychon/x11rb/blob/88e1f0b3a35a7ca3c15efb5aaf4a4f22e6b1abd1/src/rust_connection/inner.rs#L206-L211

**Comment by dalcde** [comment]
One option is to give up and return Box<dyn Error>.
