### ISSUE TITLE
Add a prelude

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#17]
It would be nice to have a `prelude` module so that most code could get away with `use x11rb::prelude::*;`.

(But before actually creating such a module, more examples should be written to figure out what should and shouldn't be in the prelude.)

**Comment by psychon** [comment]
Is it worth having a prelude? Somehow I read a lot of advice towards "don't do that" recently. So perhaps this issue should just be closed.

**Comment by eduardosm** [comment]
I personally don't like preludes because I like to have more control of what gets imported into my namespace. I also think that wildcard imports will hide things from the programmer. For example:
```rust
use some_lib::prelude::*;
use other_lib::prelude::*;

// Where does this `Connection` come from?
// (I now that this would be an error if both wildcards imported
// a `Connection`, but it still won't be obvious for someone who
// don't know the libraries).
fn do_something(conn: &Connection) {
    ...
}
```
