### ISSUE TITLE
Allow access to the raw XCB connection

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#18]
Something like this:
```rust
pub fn get_raw_conn(&self) -> *mut xcb_connection_t;
pub fn into_raw_conn(self -> *mut xcb_connection_t;
```
Perhaps also `from_raw_conn`?

**Comment by antonok-edm** [comment]
Not sure if you've seen it before, but I highly recommend using the [raw-window-handle](https://github.com/rust-windowing/raw-window-handle) crate for this API - you'll gain compatibility with a lot of existing graphics/windowing libraries for free.

**Comment by psychon** [comment]
@antonok-edm Thanks for the suggestion. However, since the `xcb_connection_t` does not refer to any specific window, so I do not think that `raw-window-handle` help much here. Instead, one gets a `*mut libc::c_void` and can construct an instance of `raw-window-handle` oneself.
