### ISSUE TITLE
From vs Into

### ISSUE THREAD

**Issue by dalcde** [psychon/x11rb#187]
With Rust 1.41, there is no reason to implement `Into` instead of `From`. Should the code generator always generate `From` instead of `Into`?

**Comment by psychon** [comment]
You are referring to the following, right?

https://github.com/rust-lang/rust/blob/master/RELEASES.md
> - [You can now pass type parameters to foreign items when implementing
>   traits.][65879] E.g. You can now write `impl<T> From<Foo> for Vec<T> {}`.

If so, that would mean bumping the minimum required rust version. It is currently 1.37.0.

[65879]: https://github.com/rust-lang/rust/pull/65879/

**Comment by dalcde** [comment]
I just realized that all current instances of `impl Into` can be replaced with `impl From` even without the recent change. Submitting PR for that.
