### ISSUE TITLE
Have pre-generated source code in releases?

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#190]
This started with #189. Apparently CLion cannot see the generated code in this crate and thus "has less features". A way around this would be to ship the generated code with releases and omit it from git. However, it is not clear how this can be achieved.

I took a look at wayland-rs and they seem to just always generate code.

One could have a check in `build.rs` to see if the generated code is already there and do nothing. This would then somehow have to be integrated with `cargo publish` (apparently one can specify files to include in `Cargo.toml`). However, this has the problem on how to figure out if code needs to be re-generated.

**Comment by JoHaHu** [comment]
This says it should be fixed in next release.
https://github.com/intellij-rust/intellij-rust/issues/4627

**Comment by psychon** [comment]
Another option: Just have the generated code in Git. Travis would complain if it is out of date. At the beginning of each file, there would be a comment saying something like "Generated code. Do not edit. Run `make` to regenerate this".
