### ISSUE TITLE
Add buffering to RustConnection

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#194]
Currently, `RustConnection` is unbuffered (no `BufReader` and no `BufWriter`). Performance-wise, it might make sense to change this and add some buffering. However, I am not quite sure how. Do I need to `try_clone` my `TcpStream`/`UnixStream` and wrap one half in a `BufReader` and the other in a `BufWriter`? Alternatively, `&TcpStream` also implements `Read`/`Write`, so can this be used somehow? (But I would expect borrowing problems due to both `BufReader` and `BufWriter` wanting exclusive access to the underlying stream...)

Edit: Of course, this means that `RustConnection::flush()` needs to be wired up correctly, too.

**Comment by dalcde** [comment]
The bufstream crate solves this issue. The idea is that you can access the underlying writer from BufWriter via get_mut, so you implement Read on (a wrapper around) BufWriter via get_mut and then do BufReader<BufWriter<W>>. It is easy to roll this yourself if you don't want an additional dependency.

**Comment by psychon** [comment]
Thanks for that explanation. It works and... it's ugly.

Anyway, this issue will most likely soon go away when I fix the following:
https://github.com/psychon/x11rb/blob/1793ae562eb6a3ffe1702c48ba77db0381495b21/src/rust_connection/inner.rs#L154-L155

Basically: The X11 server may stop reading from a client (if the client does not read the replies from the server). Thus, we must never do blocking `write` calls. libxcb handles this with `select()` and `poll()`. This is Unix-only and not easily accessible in Rust. So, I think I will go the easy route and have `RustConnection` create a background thread that always does all the necessary reading.

When that thread exists, this issue goes away (and `get_mut` is not an option then, because threads).

**Comment by psychon** [comment]
Fixed by 80e5be9a03732a131ccadafd73f5a24516283c9e
