### ISSUE TITLE
RustConnection: Never block in writing without reading

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#222]
https://github.com/psychon/x11rb/blob/master/src/rust_connection/inner.rs#L177-L178

The X11 server may stop reading from a client if a lot of data is still pending to be sent to the client. Thus, a X11 client may not block while writing, but must always be able to also read from the connection. Otherwise, dead-locks are possible (the server does not read before its output buffer is drained and the client does not read until it managed to write something). However, I guess (guess!) this is hard to hit and thus this is low-priority for now (until someone actually manages to run into this problem).

libxcb solves this problem by using `poll()` / `select()` and having its socket in non-blocking mode. That way, actually writing cannot block and a thread that wants to write is always checking for reading to be possible. I believe this is not easily possible in Rust today. Especially so if the solution should be portable (I am looking at you, Windows!).

This was previously already discussed in #199 where @dalcde suggested using `set_nonblocking` as an approximation of what needs to be done here. However, I am not sure what should happen if both reading and writing is not possible right now (both failed with "try again later"). In that case... the code would busy-loop? Do a blocking write (bad, because that's exactly what we want to avoid)? Do a blocking read (bad, because nothing guarantees that there will be something to read)?

@dalcde suggested:
1. non-blocking write; if everything was written: done!
2. non-blocking read to drain the read buffer
3. blocking write (with the assumption that this cannot cause a dead-lock since we just drained the read buffer)

I think this can work, but I cannot really guarantee it. So, instead... I am opening this issue and ignoring the problem completely.

Edit: Another possible approach is to start a thread that does the reading. So, to summarise, the possible approaches so far are:

- Ignore the problem
- Access `select()`/`poll()` (requires unsafe code, how can this be done on Windows?)
- Start a thread that does all the reading
- Do something with `set_nonblocking()`.

**Comment by eduardosm** [comment]
Another approach would be to use [mio](https://crates.io/crates/mio). It provides a platform independent equivalent to `select()`/`poll()` and does not require unsafe code.

**Comment by dalcde** [comment]
mio is a very large dependency compared to what we currently have.

**Comment by psychon** [comment]
I am thinking about depending on `nix` instead. That should be lighter than `mio` (right?). `nix` would allow to to just use `poll()` in safe rust. I guess on Windows, one just keeps the current behaviour.

A rough idea towards that would be to add another generic parameter to `RustConnection`. Let's call it `P: Poller`. This `Poller` trait (suggestions for good names welcome) could then be used to "plug in" some kind of checking. On Windows, the current behaviour would be kept by always signaling "this is writable" without actually checking. Everywhere else, another implementation would use `poll()` to actually do the check.

Oh and: I think this `Poller` is only necessary in the write path. The read path can stay the way it is.

I'll also have to think about how the two interact. Once upon a time, libxcb had a synchronisation bug here (a reader would `poll()` for reading, a writer would `poll()` for reading+writing, the writer would "steal" the packet that the reader is waiting for, and the reader would then sit forever in `poll()` and never return).

Anyway, this is a rough idea that I was thinking about.
