### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by andrewshadura** [psychon/x11rb#253]
Hi,

I need xinput(2) for the Rust port of my app, ~and currently neither xcb bindings nor your project offer it. I could, of course, use the x11 crate, but… is there any plan to add xinput support here?~
and the currently published version doesn’t seem to support it. Would you please tag a release any time soon and publish it on [crates.io](https://crates.io)?

Thanks!

**Comment by andrewshadura** [comment]
Oh, it seems there was #55 already about this and it seems to have been fixed

**Comment by andrewshadura** [comment]
So I guess this bug should really be about tagging a new release :slightly_smiling_face:

**Comment by psychon** [comment]
Oh, wow, I did not know that the xcb crate did not support xinput: https://github.com/rtbo/rust-xcb/issues/52
There is also an ancient PR with an author name that rings a bell or two: https://github.com/rtbo/rust-xcb/pull/33 ;-)

The state of xinput support here is: I worked on having the code generator not die while generating code for xinput, the generated code looking sane and `rustc` not complaining. I did not actually test anything at all with xinput. So, I'd be interested in anything you do with it (and could e.g. add a `README.md` to `examples/` that links to whatever you are doing, if you think that could be a good idea). Feel free to open issues if you have some problems.

I hope that the generated API is usable (and I think that it is a lot better than what libxcb offers), but I am also interested in any feedback here. Personally, I do not have much experience with XKB or xinput (the two extensions which needed extra magic to be expressible in xcb-proto's XML).

For your actual question of "do a new release": It's planned for tomorrow: https://github.com/psychon/x11rb/pull/241#issuecomment-593128560
I still hope generate a better changelog and then we are pretty much ready to roll.

I hope you don't mind, but I'll close this issue.

**Comment by andrewshadura** [comment]
@psychon, how about one last minute feature? I’m sorry if I’m asking for something stupid, I’m an absolute beginner with Rust.

For XInput, the following code is generated:
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq)] 
pub enum DeviceType {                        
    MasterPointer,                           
    MasterKeyboard,                          
    SlavePointer,                            
    SlaveKeyboard,                           
    FloatingSlave,                           
}                                            
impl From<DeviceType> for u8 {               
    fn from(input: DeviceType) -> Self {     
        match input {                        
            DeviceType::MasterPointer => 1,  
            DeviceType::MasterKeyboard => 2, 
            DeviceType::SlavePointer => 3,   
            DeviceType::SlaveKeyboard => 4,  
            DeviceType::FloatingSlave => 5,  
        }                                    
    }                                        
}                                            
```
This makes it possible to convert `DeviceType` into `u8`, since the implicit discriminators start at 0 and don’t match the values. First of all, the question is, why doesn’t the code generator specify explicit discriminators, but only creates the mapping in the `From` trait’s implementation? Second question: would it be possible to also introduce the reverse mapping so that it’s be possible to convert `u8`/`u16` into `DeviceType`?

Relatedly, this description:
```xml
<struct name="XIDeviceInfo"> 
    <field type="DeviceId" name="deviceid" altenum="Device" /> 
    <field type="CARD16"   name="type" enum="DeviceType" /> 
    <field type="DeviceId" name="attachment" altenum="Device" />
    <field type="CARD16"   name="num_classes" /> 
    <field type="CARD16"   name="name_len" /> 
    <field type="BOOL"     name="enabled" /> 
    <pad bytes="1" />
    <list type="char" name="name">
        <fieldref>name_len</fieldref> 
    </list>
    <pad align="4" />
    <list type="DeviceClass" name="classes">
        <fieldref>num_classes</fieldref>
    </list>
</struct>
```
is currently converted into:
```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct XIDeviceInfo {
    pub deviceid: DeviceId,
    pub type_: u16,
    pub attachment: DeviceId,
    pub enabled: bool,
    pub name: Vec<u8>,
    pub classes: Vec<DeviceClass>,
}
```
Note `u16` instead of `DeviceType`. I understand that if you generate `From` for both directions, you’d be able to also use `DeviceType` here directly?

**Comment by psychon** [comment]
>  First of all, the question is, why doesn’t the code generator specify explicit discriminators, but only creates the mapping in the From trait’s implementation?

Uhm. No idea. Feel free to add a feature request for this. From a quick look at the docs: The type is not guaranteed. https://doc.rust-lang.org/reference/items/enumerations.html says "Under the default representation, the specified discriminant is interpreted as an isize value although the compiler is allowed to use a smaller type in the actual memory layout.". We need this specifically as `u8` to send it to the server.

> would it be possible to also introduce the reverse mapping so that it’s be possible to convert u8/u16/u32 into DeviceType?

Yup, of course it's possible. I do not have much time to look into it right now. Is `DeviceType` provided as some field with a different type somewhere?

For XIDeviceInfo: Well, the code generator basically does what the python code from xcb-proto provides.

The docs for `altenum` say

> "altenum" may be one of the values contained in the enum, but it need not be.

So... wait, I am confused about what is going on here. Will have to take a look tomorrow.

**Comment by andrewshadura** [comment]
> Yup, of course it's possible. I do not have much time to look into it right now. Is DeviceType provided as some field with a different type somewhere?

Yes, in `XIDeviceInfo` :slightly_smiling_face:

> ```rust
>     pub type_: u16,
> ```

**Comment by dalcde** [comment]
The issue with specifying discriminators is that it is not unique - multiple enum variants can have the same value

**Comment by eduardosm** [comment]
Note that `type="CARD16"`, because `DeviceType` is an enum. I think that enums in xcb-proto, rather that being 'types', they are more like 'group of constants', so they are never used directly as field types.

**Comment by andrewshadura** [comment]
Hmm. I wonder why not, is it really necessary to expose the low-level implementation detail here? It makes working with those structures more difficult in some cases, e.g. when dumping their contents.

**Comment by psychon** [comment]
For your first question: `impl From<u8> for Enum` is not possible, since some kind of "invalid input handling" is necessary.  Instead, `TryFrom<Error=ParseError>` could be possible. However, at that point I think it makes more sense to have the enum implement `TryParse`. I opened #265 for this.

For your discriminators suggestion, I opened #264.

For "this field should have type `DeviceType` instead of `u16`": #263 

None of these sound like release blockers to me (they are all new features of stuff that was already like this in version 0.1.0). I'll still try to experiment a bit with these today.

I hope that I did not miss anything here.

**Comment by andrewshadura** [comment]
Thanks a lot, I can confirm this is indeed very useful. In case you’re interested, here’s my work in progress port of my project [inputplug](https://github.com/andrewshadura/inputplug):

andrewshadura/inputplug-rust@e225ff4

This code is probably not very idiomatic, so I’d welcome any feedback you have regarding the code and maybe the x11rb’s APIs and how they can be improved for this sort of usecases.

**Comment by psychon** [comment]
I took a look. I do not really have much to say, but I left some comments anyway. Nothing "really serious", just minor things (that you are of course free to ignore).

Thank you very much for using x11rb. I am happy this stuff actually works. :-)
