### ISSUE TITLE
Support FD passing in RustConnection

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#254]
Once upon a time I looked into sending FDs in Rust.

I saw the `fd_passing` crate: https://docs.rs/fd-passing/0.0.1/fd_passing/
It is quite low-level and I guess not usable for us, since it does not support sending arbitrary FDs.

There is also https://crates.io/crates/uds, which seems loosely related, but also not really.

I guess for the time being, not supporting FD passing in `RustConnection` is the best option.

Edit: One possible solution is to write traits `ReadWithFD` and `WriteWithFD` that behave similar to the `Read` and `Write` traits from std. Then, some adaptor could be added that takes a `Read` and turns it into a `ReadWithFD` (no FDs can ever be received). Similarly, writing FDs would always fail for `WriteWithFD`.

Edit: https://www.reddit.com/r/rust/comments/fkqzsn/passfd_little_crate_to_transfer_file_descriptors/ and its comments are related.

**Comment by dalcde** [comment]
What exactly makes the rust situation different from the non-rust situation?

**Comment by psychon** [comment]
This is the code that libxcb needs just to for writing stuff to the socket: https://gitlab.freedesktop.org/xorg/lib/libxcb/-/blob/704e0a91b1dece9a4cce7cfe8beaeb86a5e14267/src/xcb_conn.c#L217-282 (The rest of the function removes the data that was sent from the internal buffers, basically)

There is a special case for windows where `write_vec` is implemented by just writing each `IoSlice` separately (using the Rust terms here). For not-windows, this just calls `writev` if sending FDs is not supported. Otherwise, it needs 20 lines of code to set up the arguments for `sendmsg` before it can actually send the FDs.

I bet [all of this](https://docs.rs/nix/0.17.0/nix/sys/socket/fn.sendmsg.html) is [possible with the `nix` crate](https://docs.rs/nix/0.17.0/nix/sys/socket/enum.ControlMessage.html), but then Windows becomes a special case again.

Going down that route means that using an arbitrary `Write` for `RustConnection` is no longer possible. Well, actually, I guess this could be worked around with some `WriteFD` trait that just rejects sending FDs and otherwise "passes things on". Next, one needs to reinvent the `BufWrite` wheel.

I guess my main problem with this route is that it leaves the Rust std lib behind.
