### ISSUE TITLE
Is the (posibility of disabling) "vendor-xcb-proto" feature useful?

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#272]
I believe that being able to use the system's xcb-proto carries more problems that advantages.

For example, we need hacks like this one:
https://github.com/psychon/x11rb/blob/d92cce7935942da55a68513107b4da3af1801e19/src/extension_information.rs#L74-L76
(we don't know whether booleans will be `bool` or `u8`)

Additionally, other aspects of the resulting API (e.g., available extension requests) may also depend on the version installed by the user that is compiling x11rb.

Always using the built-in xcb-proto will guarantee that there won't be inconsistencies on different distributions with different versions of xcb-proto.

**Comment by psychon** [comment]
* `allow-unsafe-code`: Yes
* `vendor-xcb-proto`: Most likely not. If someone comes up with a fix for #190, it would definitely go. For now... well, the feature already exists, so it doesn't hurt anyone to keep it.

**Comment by eduardosm** [comment]
oops, I wanted to say "Is the (posibility of disabling) vendor-xcb-proto feature useful?", I just copy-pasted the wrong name

**Comment by eduardosm** [comment]
>  so it doesn't hurt anyone to keep it

If someone uses `default-features = false` (e.g., to disable `allow-unsafe-code`), they might forget re-enabling `vendor-xcb-proto`, getting the disadvantages I mentioned before (the developer might build their crate successfully, but some random user with a different version of xcb-proto might not).

**Comment by dalcde** [comment]
Another issue is that features are supposed to be *additive*. Suppose
 - crate A depends on crate B and crate C
 - crate B depends on `x11rb` with `vendor-xcb-proto` enabled
 - crate C depends on `x11rb` with `vendor-xcb-proto` disabled

Then under the assumption that features only add something new, crate A will be compiled with a single copy of `x11rb` with `vendor-xcb-proto` enabled, which may cause problems for crate C
