### ISSUE TITLE
Rewrite the code generator in Rust

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#279]
No idea if this really is a good idea, but to get rid of the python dependency, one could rewrite the code generator in Rust. This would likely mean starting a new crate that replaces `xcbgen` and then using that crate to write a new code generator. No idea if that's a good idea to do.

**Comment by eduardosm** [comment]
I have started to write a rust generator [here](https://github.com/eduardosm/x11rb/tree/rust-generator). `generator` contains the generator, `xcbgen-rs` contains the XML loader and `src/generated_new` contains the generated code so far.
