### ISSUE TITLE
Difference between KeyPress/ReleaseEvent.

### ISSUE THREAD

**Issue by GrudgeDuck** [psychon/x11rb#298]
[`KeyPressEvent`](https://github.com/psychon/x11rb/blob/master/src/generated/xproto.rs#L1487-L1577) seems to be the same implementation as [`KeyReleaseEvent`](https://github.com/psychon/x11rb/blob/master/src/generated/xproto.rs#L1368-L1458) . If appropriate fields are given, it can be used as `KeyReleaseEvent` as an argument of `send_event` and it works well. This is confusing for users and it is better to combine them into one struct such as `KeyEvent`. Or is there any difference between them I overlooked?

**Comment by psychon** [comment]
Well, `KeyRelease` is defined as a copy of `KeyPress`. The only difference is the opcode / "number":
https://github.com/psychon/x11rb/blob/f6ebf221ffdd48846dfbe83159b79dae73acaeb9/xcbproto-1.13-6-ge79f6b0/src/xproto.xml#L356
However, I do not think expressing these copies as copies in Rust. Something like `pub type KeyReleaseEvent = KeyPressEvent;` would work in theory, but would mean that e.g. the `Debug` implementation would print the wrong type of an event.

Also, "if appropriate fields are given", it is possible to get away with lots of "wrong" values.

`ButtonPress` and `KeyPress` are also basically the same. The only difference is the type of the `detail` field (`KEYCODE` vs `BUTTON`, but both are just aliases for `u8`).

> This is confusing for users

Why exactly is it confusing? For receiving events, I think it is really helpful that press and release events are represented as different types (even though the current necessary `match` makes this not that much of an issue, but I plan to provide a helper that "parses raw bytes for you". This would then return a different enum variant for press/release).

> and it is better to combine them into one struct such as KeyEvent

How exactly would that struct look like? Do you know if this can easily be done from the existing XML description or does it require some ad-hoc extension of the XML? I would like to keep using the existing XML and not invent my own protocol description...

**Comment by GrudgeDuck** [comment]
Thank you for replying my question.

> For receiving events, I think it is really helpful that press and release events are represented as different types

This is reasonable to represent press and release as different type. I understood.

**Comment by psychon** [comment]
Uhm... does that mean this issue should be closed?

**Comment by GrudgeDuck** [comment]
Yes. Sorry, I forgot to close this issue.

**Comment by psychon** [comment]
No problem. Thanks for bringing your question here. Feel free to ask more questions.
