### ISSUE TITLE
[Needs Rust 1.40] Mark all enums as non-exhaustive

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#306]
https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/merge_requests/7#note_445486

> So you might consider adding `#[non_exhaustive]` attribute to the enums, to prevent people from matching exhaustively on them and breaking when a new value is added. This was added in [Rust 1.40](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#%5Bnon_exhaustive%5D-structs,-enums,-and-variants).

This would require dropping Rust 1.37 support, so this is not possible for now. Still, might be a good idea in the future.

**Comment by psychon** [comment]
Random idea: Add a `I_know_what_I_am_doing_please_disable_non_exhaustive` feature to x11rb. Enums can then be marked as `#[cfg_attr(not(feature = "I_know_what_I_am_doing_please_disable_non_exhaustive"), non_exhaustive)]`. The weird name of the feature should scare away people and it would get a comment in `Cargo.toml` explaining that it only exists for Rust 1.37 compatibility, but is not meant as an API stability guarantee.

**Comment by psychon** [comment]
Okay... now that we know that we *can* do this, the question is whether we *should* do this. E.g. in 2011 RENDER 0.11 PDF blend modes where added to `render`'s `PictOp`. However, `xproto`'s `ImageOrder` will never change and is useful for `match`ing. Hm...

How about only doing this for extensions and leaving out `#[non_exhaustive]` for `xproto`? Anyone has a better idea than this?

**Comment by eduardosm** [comment]
If an enum could have new values added, does it mean that we might have future cases of https://github.com/psychon/x11rb/issues/458?

**Comment by psychon** [comment]
Not really, I guess. X11 extensions must (should?) be backwards compatible. Thus, a client announcing that it only supports the old version of the extension should also only get the old enum values.

The one example I know about (RENDER 0.11) added new values that were only used in client requests. That wouldn't cause the kind of problems that #458 is about.
