### ISSUE TITLE
Parsing fixed-size events can fail

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#321]
Currently, fixed-sized events (i.e., non-ge) implement `From` to parse them. However, in some cases parsing can still fail if they contain an enum field.

For example, the `MappingNotify` event:
```rust
pub struct MappingNotifyEvent {
    pub response_type: u8,
    pub sequence: u16,
    pub request: Mapping,
    pub first_keycode: Keycode,
    pub count: u8,
}
```

Even if the wire data has 32 bytes, parsing the field `request` might fail if it has an invalid value.

**Comment by psychon** [comment]
Oh, that's new. Thanks for catching this. Since this means breaking API, it should be done "soon-ish".

Luckily, `ConnectionError` already has a `ParseError` variant, we can just change the `Into<[u8; 32>]` bound for `send_event()` into `TryInto`.

**Comment by eduardosm** [comment]
Why changing the bound in `send_event()`? Serializing fixed-size events should still be fine.

**Comment by psychon** [comment]
Oh, sorry. I mixed up parsing and serialising. I guess only event parsing makes use of this trait implementation currently.
