### ISSUE TITLE
Another of those pesky missed expression checks: xinput, DeviceClass, button, state

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#355]
From `xinput.xml` (this appears in `<struct name="DeviceClass">`):
```xml
	    <case name="button">
		<enumref ref="DeviceClassType">Button</enumref>
		<required_start_align align="4" offset="2" />
		<field type="CARD16"   name="num_buttons" />
		<list type="CARD32"    name="state">
		    <op op="/">
		        <op op="+">
		            <fieldref>num_buttons</fieldref>
		            <value>31</value>
		        </op>
		        <value>32</value>
		    </op>
		</list>
		<list type="ATOM" name="labels">
		    <fieldref>num_buttons</fieldref>
		</list>
	    </case>
```
The relevant code for serialisation of this case does not check that this (weird) expression holds:
```rust
impl Serialize for DeviceClassDataButton {
    [...]
    fn serialize_into(&self, bytes: &mut Vec<u8>) {
        let num_buttons = u16::try_from(self.labels.len()).expect("`labels` has too many elements");
        num_buttons.serialize_into(bytes);
        self.state.serialize_into(bytes);
        self.labels.serialize_into(bytes);
    }
}
```
I think this needs an `assert_eq!(self.state.len(), (self.labels.len() + 31) / 32, "nice message here");` or something like that.

**Comment by eduardosm** [comment]
I think those were also missing in the original definitions. These are harder to implement, because there can be `<paramref>`s. Switches can also have `<fieldref>`s that refer to fields outside the switch.

**Comment by psychon** [comment]
Yup, they were missing before. Sorry if I not made this clear, but I noticed this while looking through the diffs (by the way: I am done and I do not ever want to do that again; thanks for making these diffs smaller and thanks for all the nice improvements).
