### ISSUE TITLE
New code generator: Switch back case name for switch?

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#356]
From the XML for xinput's `DeviceClass` struct:
```xml
	    <case name="key">
		<enumref ref="DeviceClassType">Key</enumref>
		<required_start_align align="4" offset="2" />
		<field type="CARD16"   name="num_keys" />
		<list type="CARD32" name="keys">
		    <fieldref>num_keys</fieldref>
		</list>
	    </case>
```
With the switch to the new code generator, the following difference occurred:
```diff
@@ -9697,7 +9712,7 @@ impl Serialize for DeviceClassDataTouch {
 }
 #[derive(Debug, Clone, PartialEq, Eq)]
 pub enum DeviceClassData {
-    Key(DeviceClassDataKey),
+    Keys(Vec<u32>),
     Button(DeviceClassDataButton),
     Valuator(DeviceClassDataValuator),
     Scroll(DeviceClassDataScroll),
```
Removing `DeviceClassDataKey` is obviously a good idea (it only had a `Vec<u32>` member), but I am not sure if renaming the variant from `Key` (which is based on `<case name="key">` to `Keys` (based on the name of the only field) is a good thing. In this case it is quite harmless, but in other cases it might lead to confusion.

**Comment by psychon** [comment]
This diff looks like it might cause confusion:
```diff
@@ -3894,7 +3908,7 @@ impl Serialize for FeedbackCtlDataBell {
 pub enum FeedbackCtlData {
     Keyboard(FeedbackCtlDataKeyboard),
     Pointer(FeedbackCtlDataPointer),
-    String(FeedbackCtlDataString),
+    Keysyms(Vec<xproto::Keysym>),
     IntToDisplay(i32),
     Led(FeedbackCtlDataLed),
     Bell(FeedbackCtlDataBell),
```
Relevant XML:
```xml
            <case name="string">
                <enumref ref="FeedbackClass">String</enumref>
		<pad bytes="2" />
		<field type="CARD16" name="num_keysyms" />
		<list type="KEYSYM"  name="keysyms">
		    <fieldref>num_keysyms</fieldref>
		</list>
            </case>
```
(No idea what "string" or "keysyms" means here or how they are related)

**Comment by eduardosm** [comment]
Agreed, this seems to be confusing. I think it might even be a good idea to bring back structs for named switch (bit)cases with a single field, so neither the name of the case nor the name of the field are lost.
