### ISSUE TITLE
`RawFdContainer` seems to be unsound

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#363]
`RawFdContainer` allows to wrap and close arbitrary file descriptors, which does not seem very safe. In fact, the standard library has [this](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html), where the `from_raw_fd` method is unsafe.

The solution would be to make `RawFdContainer::new` unsafe, remove `impl<T: IntoRawFd> From<T> for RawFdContainer`, and possibly implement `std::os::unix::io::FromRawFd` for `RawFdContainer`.

**Comment by psychon** [comment]
> RawFdContainer allows to wrap and close arbitrary file descriptors, which does not seem very safe.

Why? How can this lead to memory unsafety? This sounds weird and I have no idea on how an example could look like.

From the docs:

> This function is also unsafe as the primitives currently returned have the contract that they are the sole owner of the file descriptor they are wrapping. Usage of this function could accidentally allow violating this contract which can cause memory unsafety in code that relies on it being true.

Well, `RawFdContainer` does not allow violating the "sole owner" stuff...

**Comment by eduardosm** [comment]
> Well, `RawFdContainer` does not allow violating the "sole owner" stuff...

A `RawFdContainer` will close the FD when dropped, that's "taking ownership".

> Why? How can this lead to memory unsafety? This sounds weird and I have no idea on how an example could look like.

Something like this:
* A `std::fs::File` (well call it `file`) is created, allocating a FD number.
* A `RawFdContainer` is created with `RawFdContainer::new(file.as_raw_fd())`
* The `RawFdContainer` is dropped, closing the FD, but `file` is still living with a dangling FD.

At this point, trying to do something with `file` will cause an `EBADF`, which is not "that bad" in terms of safety. However, if a new resource that allocates a FD is open, it might reuse the FD number. In that case, operations on `file` will unexpectedly affect that new resource.

**Comment by psychon** [comment]
Random shower thought: A combination of `AsRawFd` and `libc::dup` instead.. That way, `RawFdContainer` would create its own copy of the FD. Any unsafety that stems from concurrent use of the same file descript*ion* would stay, but at least any unsafety related to same file descrip*ors* would go away.

This could also lead to a possibly slightly nicer API. Instead of requiring arguments of type `impl Into<RawFdContainer>`, the code could use `&impl AsRawFd` for the arguments.
Alternatively: Is is possible to `impl<T> Into<RawFdContainer> for &T`? Would that be better? (and another impl for the `T` instead of `&T` case).

**Comment by eduardosm** [comment]
> Is is possible to `impl<T> Into<RawFdContainer> for &T`?

`dup` can fail, so it would need to be a `TryInto`.

I think it would be safe to provide traits to convert from individual types (such as `impl From<std::fs::File>`).

So far, I created https://github.com/psychon/x11rb/pull/386, which is still WIP

**Comment by psychon** [comment]
Random data point: `nix::unistd::close` is safe: https://docs.rs/nix/0.17.0/nix/unistd/fn.close.html

The scenario from https://github.com/psychon/x11rb/issues/363#issuecomment-618456200 is possible without `RawFdContainer`. Thus, I feel like either `nix::unistd::close` is unsound or the current `RawFdContainer` is sound.

**Comment by eduardosm** [comment]
> Random data point: `nix::unistd::close` is safe: https://docs.rs/nix/0.17.0/nix/unistd/fn.close.html
> 
> The scenario from [#363 (comment)](https://github.com/psychon/x11rb/issues/363#issuecomment-618456200) is possible without `RawFdContainer`. Thus, I feel like either `nix::unistd::close` is unsound or the current `RawFdContainer` is sound.

I would say that `nix::unistd::close` is unsound. They also have `nix::unistd::write`, which feels like something that allows writing into a `mmap`ed FD without much control...

**Comment by eduardosm** [comment]
I'm closing this given the reasoning in https://github.com/nix-rust/nix/issues/1225

**Comment by psychon** [comment]
Ah, thanks for opening that issue. That's indeed a helpful description.

**Comment by psychon** [comment]
Possibly related: https://github.com/rust-lang/rust/issues/72175
