### ISSUE TITLE
Weird build errors that previously did not occur

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#374]
I am quite certain that I did not cause any of the following and yet this occurs in #373. 

<details><summary>Unused variable and private fields in `xcb_ffi` on AppVeyor:</summary>
<pre>
warning: unused variable: `sequence`
   --> src\xcb_ffi\mod.rs:472:9
    |
472 |         sequence: SequenceNumber,
    |         ^^^^^^^^ help: consider prefixing with an underscore: `_sequence`
    |
    = note: `#[warn(unused_variables)]` on by default
warning: unused variable: `sequence`
   --> src\xcb_ffi\mod.rs:472:9
    |
472 |         sequence: SequenceNumber,
    |         ^^^^^^^^ help: consider prefixing with an underscore: `_sequence`
    |
    = note: `#[warn(unused_variables)]` on by default
error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:183:13
    |
183 |             iov_base: null_mut(),
    |             ^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:184:13
    |
184 |             iov_len: 0,
    |             ^^^^^^^^^^ field `iov_len` is private
error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:187:13
    |
187 |             iov_base: null_mut(),
    |             ^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:188:13
    |
188 |             iov_len: 0,
    |             ^^^^^^^^^^ field `iov_len` is private
error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:191:13
    |
191 |             iov_base: ioslice.as_ptr() as _,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:192:13
    |
192 |             iov_len: ioslice.len().try_into().unwrap(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `iov_len` is private
error: aborting due to 6 previous errors
For more information about this error, try `rustc --explain E0451`.error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:183:13
    |
183 |             iov_base: null_mut(),
    |             ^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:184:13
    |
184 |             iov_len: 0,
    |             ^^^^^^^^^^ field `iov_len` is private
error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:187:13
    |
187 |             iov_base: null_mut(),
    |             ^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:188:13
    |
188 |             iov_len: 0,
    |             ^^^^^^^^^^ field `iov_len` is private
error: could not compile `x11rb`.
Caused by:
  process didn't exit successfully: `rustc --crate-name x11rb --edition=2018 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg "feature=\"allow-unsafe-code\"" --cfg "feature=\"default\"" --cfg "feature=\"libc\"" -C metadata=8bdc287054b58e59 -C extra-filename=-8bdc287054b58e59 --out-dir C:\projects\x11rb\target\debug\deps -C incremental=C:\projects\x11rb\target\debug\incremental -L dependency=C:\projects\x11rb\target\debug\deps --extern gethostname=C:\projects\x11rb\target\debug\deps\libgethostname-6b9bd5b3d4bf564b.rmeta --extern libc=C:\projects\x11rb\target\debug\deps\liblibc-a2b3a4e4e5dbe846.rmeta` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error[E0451]: field `iov_base` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:191:13
    |
191 |             iov_base: ioslice.as_ptr() as _,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `iov_base` is private
error[E0451]: field `iov_len` of struct `xcb_ffi::raw_ffi::iovec` is private
   --> src\xcb_ffi\mod.rs:192:13
    |
192 |             iov_len: ioslice.len().try_into().unwrap(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `iov_len` is private
error: aborting due to 6 previous errors
For more information about this error, try `rustc --explain E0451`.
error: could not compile `x11rb`.
</pre>
</details>
<details><summary>Clippy warnings in the code generator (this also occurs on builds on master, so I guess the CI here is broken in that these errors do not make the build fail)</summary>
<pre>
    Checking x11rb-generator v0.0.0 (/home/travis/build/psychon/x11rb/generator)
error: this `else { if .. }` block can be collapsed
    --> generator/src/generator/namespace.rs:3819:24
     |
3819 |                   } else {
     |  ________________________^
3820 | |                     if let Some(ref operand) = sum_of_expr.operand {
3821 | |                         format!(
3822 | |                             "{}.iter().try_fold(0u32, |acc, x| \
...    |
3833 | |                     }
3834 | |                 }
     | |_________________^
     |
     = note: `-D clippy::collapsible-if` implied by `-D warnings`
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if
help: try
     |
3819 |                 } else if let Some(ref operand) = sum_of_expr.operand {
3820 |                     format!(
3821 |                         "{}.iter().try_fold(0u32, |acc, x| \
3822 |                         acc.checked_add({}).ok_or(ParseError::ParseError))?",
3823 |                         rust_field_name,
3824 |                         self.expr_to_str(operand, panic_on_overflow, true, true),
   ...
error: this `else { if .. }` block can be collapsed
    --> generator/src/generator/namespace.rs:3819:24
     |
3819 |                   } else {
     |  ________________________^
3820 | |                     if let Some(ref operand) = sum_of_expr.operand {
3821 | |                         format!(
3822 | |                             "{}.iter().try_fold(0u32, |acc, x| \
...    |
3833 | |                     }
3834 | |                 }
     | |_________________^
     |
     = note: `-D clippy::collapsible-if` implied by `-D warnings`
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if
help: try
     |
3819 |                 } else if let Some(ref operand) = sum_of_expr.operand {
3820 |                     format!(
3821 |                         "{}.iter().try_fold(0u32, |acc, x| \
3822 |                         acc.checked_add({}).ok_or(ParseError::ParseError))?",
3823 |                         rust_field_name,
3824 |                         self.expr_to_str(operand, panic_on_overflow, true, true),
   ...
error: aborting due to previous error
error: could not compile `x11rb-generator`.
</pre>
</details>

**Comment by psychon** [comment]
Trying to fix the Travis clippy stuff in #375. The xcb "stuff" still confuses me: It does not occur in the build for that branch/PR?!?

**Comment by eduardosm** [comment]
I think this is due to [this change](https://github.com/psychon/x11rb/pull/373/files#diff-180360612c6b8c4ed830919bbb4dd459R17), which builds with default features (and thus, with `allow-unsafe-code`).
