### ISSUE TITLE
[Feature] Allow mapping of Cookies

### ISSUE THREAD

**Issue by exit91** [psychon/x11rb#380]
I want to be able to write a derivative of a `get_property` request, e.g. `get_text_property`, which returns a cookie.

Specifically `get_text_property` should return (modulo errors) some `Cookie<'_, C, GetTextPropertyReply>`, but I only have a `Cookie<'_, C, GetPropertyReply>` and a way to turn `GetPropertyReply` into a `GetTextPropertyReply`:
```rust
fn transform(GetPropertyReply) -> Result<GetTextPropertyReply, ParseError>
```

Ideally there is a way to map a cookie
```rust
let new_cookie = cookie.map(transform)

fn map(Cookie<'a, C, S>, Fn(S) -> T) -> MapCookie<'a, C, T>;
```
This approach would require Cookie to become a trait.

Alternatively one could implement something like

```rust
impl<'a, C, S, T> From<Cookie<'a, C, S>> for Cookie<'a, C, T>
where
    C: RequestConnection,
    S: for<'b> TryFrom<&'b [u8], Error = ParseError>,
    T: for<'b> TryFrom<&'b [u8], Error = ParseError>,
{
    fn from(cookie: Cookie<'a, C, S>) -> Self {
        // change phantom type
        unimplemented!()
    }
}
```

But that does seem unsafe, because we cannot guarantee that replies for type `S` will not result in garbage when interpreted by type `T`.

**Comment by psychon** [comment]
I'm curious: How did you solve this problem for you?

So far, when I needed this, I went with a newtype around the cookie:
https://github.com/psychon/x11rb/blob/c890ddb29685074e64d9ccc4a82834166b8f2880/src/properties.rs#L17
This newtype then had to implement `reply` and `reply_unchecked` functions:
https://github.com/psychon/x11rb/blob/c890ddb29685074e64d9ccc4a82834166b8f2880/src/properties.rs#L36-L48

**Comment by exit91** [comment]
Yes I do pretty much the same, which is just a minor inconvenience because I ultimately only need one or two methods provided by Cookie.
