### ISSUE TITLE
Remove generic parameter from `protocol::{Event,Error}`?

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#403]
The `protocol::Event` and `protocol::Error` are generic over the buffer type. This generic parameter is only used for the `Unknown` variant, which contains the raw event/error.

It might be worth to remove the generic parameter from `Event` and `Error` types. This would also allow removing the generic parameter from error types in the `errors` module. The parse functions would just take a `&[u8]` and the `Unknown` variant would contain a `Vec<u8>`. This would require an allocation + copy when an unknown event or error is received.

However, I think that it is very unlikely to get an unknown Event/Error from the server. In order for that to happen, you would have to use some extension that is not supported by x11rb (if that exists), so it should not lead to a performance hit for most applications.

**Comment by eduardosm** [comment]
I have created https://github.com/psychon/x11rb/pull/404 (PR not found) so you can see the scope of this change, but feel free to accept or reject it.

**Comment by psychon** [comment]
> In order for that to happen, you would have to use some extension that is not supported by x11rb (if that exists), so it should not lead to a performance hit for most applications.

Or one would need a version of an extension that is not supported by x11rb...

Anyway, if "one copy in event/error reception" leads to a performance hit, then something is seriously wrong somewhere :-)
