### ISSUE TITLE
Disable XCBConnection by default?

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#407]
Via https://crates.io/crates/x11rb/reverse_dependencies I came across https://github.com/neXromancers/uniconize/blob/1f6890befa02f8cbf7b8fe4e00b1958c40511ba3/Cargo.toml#L10-L13:
```
[dependencies.x11rb]
version = "0.4"
default-features = false
features = ["vendor-xcb-proto"]
```
This made me wonder "why `disable-features=false`? This disables `XCBConnection`.

Since `RustConnection` now "can do everything", does it make sense to disable `XCBConnection` by default? That way, the dependency on `libxcb.so` also goes away.

**Comment by eduardosm** [comment]
I believe that the main reason to use `XCBConnection` is to interact with other libraries that need a `xcb_connection_t`, so I think it can be removed from default features.
