### ISSUE TITLE
Broken link in doc/comparison.md for generated_code.md

### ISSUE THREAD

**Issue by spazm** [psychon/x11rb#413]
The link for doc/generated_code.md is broken: 

> `[can be found here](doc/generated_code.md)`

1. The link should not contain `doc/` as that is the same directory as `comparison.md`.
2. The `generated_code.md` file was deleted in 5032e900b758ba4f216b5763f3975e41eb5e4ee7

I went back and read the deleted file.  FWIW, I found it interesting and appreciated the prose around the code samples.

**Comment by spazm** [comment]
The `doc/` is left over from when this file was split out from the readme file in 483f2befe8f9d5717a9783ab91c5bc202665a23b

**Comment by psychon** [comment]
> FWIW, I found it interesting and appreciated the prose around the code samples.

Hm. This issue just became a lot more complicated. Instead of just getting rid of this broken link, I'll have to think about whether this convenience is worth the extra maintenance burden (the examples of the generated code are almost always outdated (at least that's how I remember the situation)).
