### ISSUE TITLE
xkb_get_map fails when using XCBConnection made in x11rb, but not one from raw xcb connection

### ISSUE THREAD

**Issue by JuanPotato** [psychon/x11rb#432]
Hi, i was working on a program that used the xkb_get_map function and in the beginning I also needed to use xlib functions so I opened a display, got an xcb connection, and then passed that raw connection to x11rb. The code looked something like this.

```rust

use x11rb::xcb_ffi::XCBConnection;
use x11rb::protocol::xkb::{ConnectionExt as XkbConnectionExt, MapPart, ID};

let conn = unsafe {
    // Open display connection.
    let dpy = x11::xlib::XOpenDisplay(std::ptr::null());
    if dpy.is_null() {
        panic!("Could not open display");
    }

    let xcb_conn = x11::xlib_xcb::XGetXCBConnection(dpy);
    if xcb_conn.is_null() {
        panic!("Could not cast display to xcb connection");
    }

    XCBConnection::from_raw_xcb_connection(xcb_conn, true).unwrap()
};

let get_map_cookie = conn.xkb_get_map(
    ID::UseCoreKbd as u16,
    (MapPart::KeyTypes
         | MapPart::KeySyms
         | MapPart::ModifierMap
         | MapPart::ExplicitComponents
         | MapPart::KeyActions
         | MapPart::KeyBehaviors
         | MapPart::VirtualMods
         | MapPart::VirtualModMap
    ) as u16,
    0u16, 0, 0, 0, 0, 0, 0, 0, 0, 0u16, 0, 0, 0, 0, 0, 0)
    .unwrap();

let get_map_reply = get_map_cookie.reply().unwrap();

```

This code works on my machine as I expect it to. Once I cleaned up all the uses of xlib in my code, I figured I no longer need to make a display and then grab the raw xcb, connection, so I did that but then it caused my code to break. This is the new code.

```rust

use x11rb::xcb_ffi::XCBConnection;
use x11rb::protocol::xkb::{ConnectionExt as XkbConnectionExt, MapPart, ID};

let conn = XCBConnection::connect(None).unwrap().0;

let get_map_cookie = conn.xkb_get_map(
    ID::UseCoreKbd as u16,
    (MapPart::KeyTypes
         | MapPart::KeySyms
         | MapPart::ModifierMap
         | MapPart::ExplicitComponents
         | MapPart::KeyActions
         | MapPart::KeyBehaviors
         | MapPart::VirtualMods
         | MapPart::VirtualModMap
    ) as u16,
    0u16, 0, 0, 0, 0, 0, 0, 0, 0, 0u16, 0, 0, 0, 0, 0, 0)
    .unwrap();

let get_map_reply = get_map_cookie.reply().unwrap();

```

It is much nicer now, but it doesn't work :(.

Specifically, it breaks because the reply is an error
```rust

X11Error(Access(RequestError { response_type: 0, error_code: 10, sequence: 2, bad_value: 0, minor_opcode: 8, major_opcode: 135 }))

```

It'd be nice to be able to not depend on xlib to create the display first, but I'm not sure what to do from here as I have very little knowledge about x11.

**Comment by psychon** [comment]
Ah, you had me confused for a moment, but I think I know what is going on.

Inside of `XOpenDisplay`, the function `XkbUseExtension` is called: https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/fb65b67169105c82c243f265e0f993cf72efdacd/src/OpenDis.c#L561

This function sends an `UseExtension` XKB request: https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/fb65b67169105c82c243f265e0f993cf72efdacd/src/xkb/XKBUse.c#L750-754
This request basically says "dear X11 server, I want to talk XKB 1.0 with you". I bet that one has to send this request before any other XKB request can be used. At least the protocol reference says so:

> If a client attempts to use any other XKB request except XkbUseExtension before the extension is properly initialized, XKB reports an Access error and ignores the request. XKB is properly initialized once XkbUseExtension reports that the client has asked for a supported or compatible version of the extension.

https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html

According to `xtrace gvim`, the following is sent with Xlib:
```
000:<:0006:  8: XKEYBOARD-Request(135,0): UseExtension major=1 minor=0
000:>:0006:32: Reply to UseExtension: major=1 minor=0
```
With the following patch to your code, things start working:
```diff
diff --git a/src/main.rs b/src/main.rs
index 60b5da1..f4c5764 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,9 +1,12 @@
 fn main() {
 use x11rb::xcb_ffi::XCBConnection;
-use x11rb::protocol::xkb::{ConnectionExt as XkbConnectionExt, MapPart, ID};
+use x11rb::protocol::xkb::{self, ConnectionExt as XkbConnectionExt, MapPart, ID};
 
 let conn = XCBConnection::connect(None).unwrap().0;
 
+let ver = xkb::X11_XML_VERSION;
+conn.xkb_use_extension(ver.0 as _, ver.1 as _).unwrap();
+
 let get_map_cookie = conn.xkb_get_map(
     ID::UseCoreKbd as u16,
     (MapPart::KeyTypes
```
The cast from `u32` to `u16` is a bit unfortunate. You can also just write `1` and `0`. This goes back to #130 where apparently we figured out that most `QueryVersion` requests take `u32` as argument.

**Comment by JuanPotato** [comment]
Thanks for the fast response!

https://github.com/neXromancers/oxdo/ This is the project that the code belongs to in case you're interested
