### ISSUE TITLE
impl std::error::Error for errors

### ISSUE THREAD

**Issue by jneem** [psychon/x11rb#466]
It would be very handy for error-handling using `?` if the various error types implemented `std::error::Error`.

**Comment by psychon** [comment]
Uhm... they do? Could you clarify what you mean?
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L13
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L59
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L135
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L176
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L232

**Comment by jneem** [comment]
Specifically, the one I wanted today was `x11rb::protocol::Error`, which according to the [0.5.0 docs](https://docs.rs/x11rb/0.5.0/x11rb/protocol/enum.Error.html) doesn't implement `std::error::Error`. I also clicked through the first few of the enum options on `x11rb::protocol::Error`, and didn't see `std::error::Error` impls for them either.

**Comment by psychon** [comment]
Ah, yeah. None of them implement `Error'. However, they should not really ever appear as the error type in a `Result`. For this, there is `ReplyError':
https://github.com/psychon/x11rb/blob/395694e0e5fbc80c8046bba0b1350ae3f28abc14/src/errors.rs#L167-L174
The `Error` enum and its members are the actual errors that are sent by the X11 server. They are not really errors in the `std::error::Error` sense, I think. Implementing `std::error::Error` for this enum would require implementing `Display` for them, which I do not think makes much sense. What's the "right" way to format one of these errors for "human display"?

`ReplyError` just uses the `Debug` output, but at least it adds some hint that this is an X11 error sent by the X11 server...

Can I ask how you end up with `?` on `Error`?

**Comment by jneem** [comment]
I didn't actually end up with a `Result`, but I got an `Error` through `VoidCookie::check`. Specifically, I had something like
```rust
if let Some(err) = conn.create_window(...)?.check() {
    return Err(err.into())
}
```
and if `Error` had implemented `std::error::Error` then the `into()` would have worked because I'm calling this in a function returning `anyhow::Error`. (Actually, now that I know a `ReplyError` is either a `ConnectionError` or an `Error`, is there some reason `check` doesn't return `Result<(), ReplyError>`?

I guess one workaround is for me to wrap it in a `ReplyError`.

As for `Display`, is there a "right" way to format any error? I think the goal of `Display` is just to enable troubleshooting, and so one reasonable option is to do some variant of the classical libX11 error:
```
X Error: BadRequest (invalid request code or no such operation) 1
Extension: 198 (Uknown extension)
Minor opcode: 0 (Unknown request)
Resource id: 0x600082
```

**Comment by psychon** [comment]
> VoidCookie::check

Hm... That functions is `pub fn check(self) -> Result<Option<Error>, ConnectionError>`. Locally, this makes sense. This function returns an optional error, but getting this error "could go wrong" because the connection breaks.

Should this perhaps be changed into `Result<(), ReplyError>`? What would be the pros & cons of that?

**Comment by jneem** [comment]
You described `check` as trying to get an error, but I was thinking of it differently: I want to check if the operation (creating a window) succeeded. If it succeeded then that's good; otherwise I would need to handle the error.

In my use-case, if I fail to create a window, I want to display an error and bail out. I don't particularly care whether the error came from the connection or the X server. For this use case, if the return were `Result<(), ReplyError>`, I could just do
```rust
conn.create_window(...)?.check()?;
```

On the other hand, there are some other things I might want to do. Like, bail on a connection error but handle the X11 error.
```rust
// With the current signature:
if let Some(err) = conn.create_window(...)?.check()? {
   ...
}

// With the proposed signature:
match conn.create_window(...)?.check() {
    Err(ReplyError::XError(e) => {...},
    other => other?,
}
```
I think this looks nicer with the current signature.

Or you could handle the connection error and bail on the X error (I'm not sure if this is realistic, though).
```rust
// With the current signature:
match conn.create_window(...)?.check() {
    // I'm wrapping in ReplyError, so that it implements std::error::Error.
    Ok(Some(err)) => return Err(ReplyError::XError(err)),
    Err(e) => { ... },
    _ => {},
}

// With the proposed signature:
match conn.create_window(...)?.check() {
    Err(ReplyError::ConnectionError(e) => {...},
    other => other?,
}
```
I think this is clearer with the proposed signature.

Here is what it would look like to handle both errors
```rust
// With the current signature:
match conn.create_window()?.check() {
    Err(e) => //handle connection error,
    Ok(Some(e)) => //handle X error,
    _ => {},
}

// With the proposed signature:
match conn.create_window()?.check() {
    Err(ReplyError::ConnectionError(e)) => // handle connection error
    Err(ReplyError::XError(e)) => // handle X error
    Ok(()) => {},
}
```
With the proposed signature, this is a little longer, but I think it's more self-documenting.

Overall, the proposed signature is nicer if you want to bail on both kinds of errors or if you want to handle just the connection errors, the current signature is nicer if you want to handle X errors and bail on connection errors, and the situation for handling both kinds of errors is less clear.
