### ISSUE TITLE
include the cairo glue code?

### ISSUE THREAD

**Issue by jneem** [psychon/x11rb#467]
I appreciate the cairo-example that you give. Is there any chance that the glue code it contains (i.e. the definition of `xcb_visual_type_t`, the `From` impl, and maybe a convenience function for doing the cairo surface creation) could be part of the main crate (probably behind a feature flag). I realize I could just copy-paste from the example (and I will, for now), but it would be nicer not to have to.

**Comment by psychon** [comment]
You can use the `xcb` crate. It provides the necessary FFI for `xcb_visual_type_t`. See https://github.com/psychon/x11rb/issues/328#issuecomment-608984265. That gets rid of the hand-written struct definition.

**Comment by jneem** [comment]
Fair enough, but I was hoping to *replace* my `xcb` dependency with `x11rb`...

**Comment by psychon** [comment]
Adding this to x11rb feels a bit out of scope to me... How about a new `x11rb-cairo` crate instead?

However, I am not quite sure how the API for such a crate should look like. Making the API safe and ergonomic might end up being quite complicated.

**Comment by psychon** [comment]
I took a closer look. There are three ways to create a cairo-xcb surface:
- `cairo_xcb_surface_create`
- `cairo_xcb_surface_create_for_bitmap`
- `cairo_xcb_surface_create_with_xrender_format`

The last two functions take a `xcb_screen_t*` and use that in some internal cache. Thus, this needs to be a long-lived pointer. Which means one needs to actually interact with libxcb and get the `xcb_screen_t*` out from there. At this point, using the xcb crate is likely the best option here. (Also, doesn't the compiler optimise out unused code? So there is no benefit of reimplementing this.)

So there is only `cairo_xcb_surface_create` for which it might make sense to provide a binding. This would then only save "a few" lines of code which do not really fit well into the rest of x11rb and which are terribly unsafe.

I feel like copy&pasting this piece of code is the more sensible option here. Sorry.

(Everyone else: Feel free to disagree with me. Please speak up!)

**Comment by jneem** [comment]
Ok, thanks for looking into this!
