### ISSUE TITLE
Update to rostxmltree v0.12

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#494]
I just reported this as https://github.com/RazrFalcon/roxmltree/issues/36.

```
error[E0621]: explicit lifetime required in the type of `name`
    --> xcbgen-rs/src/parser.rs:1129:5
     |
1128 | fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &str) -> Result<&'a str, ParseError> {
     |                                                      ---- help: add explicit lifetime `'a` to the type of `name`: `&'a str`
1129 |     node.attribute(name).ok_or(ParseError::InvalidXml)
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'a` required
error: aborting due to previous error
```
There is just one commit that could have caused this. It is https://github.com/RazrFalcon/roxmltree/commit/1ae0c6a6f5a40b3cbb0eb74e3551f786ad42fa83
This commit adds a second lifetime to `ExpandedName`. The `attribute` function is changed like this:
```diff
     pub fn attribute<'n, N>(&self, name: N) -> Option<&'a str>
     where
-        N: Into<ExpandedName<'n>>,
+        N: Into<ExpandedName<'n, 'input>>,
```
I guess this second lifetime makes some kind of interference fail somewhere, but I do not completely understand yet what is going on.

**Comment by eduardosm** [comment]
0.11.1 has been yanked, so we can stay on 0.11 for now. I have create https://github.com/RazrFalcon/roxmltree/pull/37 to fix the issue in roxmltree.
