### ISSUE TITLE
Extract the major opcode (and maybe more things) from an error.

### ISSUE THREAD

**Issue by jneem** [psychon/x11rb#503]
As far as I can tell, most (all?) X11 errors come with a `major_opcode`. Unfortunately, if I have a `x11rb::protocol::Error`, it is difficult (AFAICT) to access it (because I need a giant match). Could a `major_opcode` method be exposed on `x11rb::protocol::Error`, just like `error_code` and `wire_sequence_number`?

My use-case for this is that if a particular extension causes an error, I want to stop using that extension and fall back to a more general method.

**Comment by psychon** [comment]
Been there, tried that gave up. Core protocol errors seem to contain that information, but extensions do not (either that or the XML descriptions are wrong and the wire format has this information, but the XML pretends otherwise).

Since I do not fully trust my own code here, here is some example from `/usr/include/xcb/randr.h`:
```c
typedef struct xcb_randr_bad_output_error_t {
    uint8_t  response_type;
    uint8_t  error_code;
    uint16_t sequence;
} xcb_randr_bad_output_error_t;
```

**Comment by psychon** [comment]
Ah, finally found the right function:
https://gitlab.freedesktop.org/xorg/xserver/-/blob/d6558477d7a264c2132bc977b51d80fc0277d1e0/dix/dispatch.c#L3740-3753
```c
void
SendErrorToClient(ClientPtr client, unsigned majorCode, unsigned minorCode,
                  XID resId, int errorCode)
{
    xError rep = {
        .type = X_Error,
        .errorCode = errorCode,
        .resourceID = resId,
        .minorCode = minorCode,
        .majorCode = majorCode
    };
    WriteEventsToClient(client, 1, (xEvent *) &rep);
}
```
`WriteEventsToClient` adds the sequence number field to the event, does some stuff (calls internal hooks, logging stuff etc) and then writes the bytes to the client.

Thus, all events have these fields and this is a bug in xcb-proto. I just reported this finding as https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/issues/16.

The plan of action here is to fix the XML description, update x11rb to a new version of xcb-proto, and then add the relevant functions to `x11rb::protocol::Error`.

**Comment by psychon** [comment]
> My use-case for this is that if a particular extension causes an error, I want to stop using that extension and fall back to a more general method.

A work around could be to instead match sequence numbers to map between errors and the request that causes them. This approach is best matched with using `wait_for_event_with_sequence()` instead of `wait_for_event()`, because that gives you the full 64 bit sequence number and not only the 16 bits that appear on the wire.

**Comment by psychon** [comment]
Another idea would be to get raw events (`wait_for_raw_event()` basically gives you a `Vec<u8>`) and then parse out the fields you need yourself. It's a bit ugly, but it would work. The major code is `data[10]`, if I counted bytes correctly (looking at the definition of `xcb_generic_error_t` in `/usr/include/xcb/xcb.h`.

You can then use `conn.parse_event()` to get the event in a "nice" form.

**Comment by jneem** [comment]
Thanks for looking into this, and for the workarounds! I think I'll punt on this for now (as you know, we have some lower-hanging fruit to address...), but I've got a link to this issue in a comment in case we revisit it later.
