### ISSUE TITLE
Can't access randr functions

### ISSUE THREAD

**Issue by ShayBox** [psychon/x11rb#506]
I can't figure out how to access https://docs.rs/x11rb/0.6.0/x11rb/protocol/randr/fn.get_screen_resources.html
Every time I try, randr does not exist on protocol

**Comment by eduardosm** [comment]
Did you enable the `randr` feature flag? https://docs.rs/x11rb/0.6.0/x11rb/index.html#feature-flags

**Comment by psychon** [comment]
@ShayBox ping? Did you have time to investigate enabling the `randr` feature?

**Comment by ShayBox** [comment]
Yeah it works now, I swear I enabled that and another feature but it worked when I re-typed it, must have just been tired
