### ISSUE TITLE
Dynamic linking

### ISSUE THREAD

**Issue by sandmor** [psychon/x11rb#522]
So, I want to use the native xcb library only because it allows me to return a raw-window-handle but I want to avoid dynamic link against libxcb for environments where there is not xcb but Wayland

**Comment by psychon** [comment]
Okay... so?
If you want to decide about this at compile time, you'll have to make your dependency on x11rb optional and only enable it when `libxcb.so` is available. When you want to decide about this at runtime... then I don't know how this should be done. Suggestions?
(Slightly unrelated, but... are there any environments were Wayland is available, but `libxcb.so` is not? This seems a bit unrealistic to me.)

**Comment by sandmor** [comment]
You can use `dlopen` and `dlsym` to get a pointer to the functions at runtime time, you can store it in lazy_static if you want
