### ISSUE TITLE
Create images

### ISSUE THREAD

**Issue by sandmor** [psychon/x11rb#523]
So I want to show an image that I generate, I have the following code for that:
```rust
            CONN.put_image(
                xproto::ImageFormat::ZPixmap,
                window.pixmap,
                window.gcontext,
                window.width,
                window.height,
                0,
                0,
                32,
                screen_depth,
                buffer,
            )
            .unwrap();

            CONN.copy_area(
                window.pixmap,
                window_id,
                window.gcontext,
                0,
                0,
                0,
                0,
                wiindow.width,
                window.height,
            )
            .unwrap();
```
I am trying to make the image cover the entire screen and draw in the image simply like `buffer[(y*width+x)*BytesPerPixel] = color`, but this code only draws a black screen, also the GC is generated like next:
```rust
xproto::CreateGCAux::new().graphics_exposures(0);
```
Maybe I had to specific more options?.
And yeah, I know that I can use shared memory for this purpose but... I want to make it without extensions

**Comment by psychon** [comment]
Well.. I do not know. Do you have a full code example to look at?

Does your event loop print errors? If I am counting arguments correctly, you are setting the `left_pad` argument for your `PutImage` request to 32. To quote https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:PutImage:

> The left-pad must be zero for ZPixmap format (or a Match error results). 

Have you seen the [display_ppm](https://github.com/psychon/x11rb/blob/master/examples/display_ppm.rs) example? This example uploads an image to a pixmap. It also only uses a GC without graphics exposures and no other options.

**Comment by sandmor** [comment]
Oh sorry, I was through of the examples but only vaguely, thank you, I will check it, by the way, can you rename this example to something like display_ppm_image or something like that? it will be useful for persons like me

**Comment by sandmor** [comment]
Yeah, I only set the `left_pad` to zero and wonder work, thank you!!
