### ISSUE TITLE
Unable to use record extension

### ISSUE THREAD

**Issue by sandorstormen** [psychon/x11rb#524]
It seems that there is no way of using the record extension with this library.
I think the [function](https://docs.rs/x11rb/0.6.0/x11rb/protocol/record/fn.enable_context.html) `x11rb::protocol::record::enable_context()` should take in a C callback function to work like the C X11 API.
In the [x11](https://crates.io/crates/x11) crate it is implemented like [this](https://crumblingstatue.github.io/doc/libxdo/x11/xrecord/fn.XRecordEnableContext.html), which allows you to pass an unsafe C callback function to the `XRecordEnableContext()` function.
Could something like this be implemented?
I know this library is for providing safer code than other X11 rust libraries, but the record extension is completely unusable in this library otherwise.
To my knowledge there is no other way of doing a C callback function in rust, without an having `unsafe  extern "C"` function.

**Comment by psychon** [comment]
See https://stackoverflow.com/questions/20823894/xcb-record-x11-extension-example for how to use the record extension with xcb. With x11rb, it will be more-or-less similar. Also, you do not want to use the record extension. ;-)

**Comment by sandorstormen** [comment]
> See https://stackoverflow.com/questions/20823894/xcb-record-x11-extension-example for how to use the record extension with xcb. With x11rb, it will be more-or-less similar. Also, you do not want to use the record extension. ;-)

Yeah I know I shouldn't use the record extension. I just haven't found any other way to globally get events from keyboard and mouse.

Does the 'get_context()' function in x11rb correspond to the 'xcb_record_enable_context_reply()' function?

**Comment by psychon** [comment]
That corresponds to the `.reply()` function on the cookie returned by `x11rb::protocol::record::enable_context`.
However, that's a request with more than one reply. That will indeed require a bit of changes to x11rb. I'm working on it.

**Comment by psychon** [comment]
PR #525 should fix this. Since the PR changes API, the example that it adds does not work with the version of x11rb currently available on crates.io. To work around that, apply the following patch to the example. That makes it work with x11rb 0.6.0.
```diff
diff --git a/src/main.rs b/src/main.rs
index 80f1967..6eb8b07 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -76,8 +76,12 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
     // FIXME: These constants should be added to the XML
     const START_OF_DATA: u8 = 4;
     const RECORD_FROM_SERVER: u8 = 0;
-    for reply in data_conn.record_enable_context(rc)? {
-        let reply = reply?;
+    let request = data_conn.record_enable_context(rc)?;
+    let seqno = request.sequence_number();
+    std::mem::forget(request);
+    loop {
+        let reply = data_conn.wait_for_reply_or_error(seqno)?;
+        let reply = record::EnableContextReply::try_from(reply.as_ref())?;
         if reply.client_swapped {
             println!("Byte swapped clients are unsupported");
         } else if reply.category == RECORD_FROM_SERVER {
```
(Proper handling would also require `if reply.category == 5 { break; }`, but since the example never sends a `DisableContext` request on the control connection, no `EndOfData` reply will ever be replaced, so this does not actually make a difference here.)
