### ISSUE TITLE
Send events

### ISSUE THREAD

**Issue by sandmor** [psychon/x11rb#526]
I'm implementing clipboard support for [a project](https://github.com/sandmor/moving) that I'm doing, but I hit a wall with the copy operation.
For that, according to [this article](https://www.uninformativ.de/blog/postings/2017-04-02/0/POSTING-en.html) I need to send an event to other window but then I had a problem, send_event function is there BUT it requests the event in raw form, and there is no a manner to make that thing currently, currently if I want to implement the copy functionality I will need to implement the event maker myself and I think that the library would provide that.
If I can suggest a manner, it would be add the method to the `Event` enum

**Comment by eduardosm** [comment]
You can pass directly the event struct to `send_event` (or a reference to the event) because most events implement `Into<[u8; 32]>`.

```rust
impl From<&KeyPressEvent> for [u8; 32] {
    ...
}
impl From<KeyPressEvent> for [u8; 32] {
    ...
}
// Into<[u8; 32]> for KeyPressEvent and &KeyPressEvent are deduced from those

pub fn send_event<Conn, A, B, C>(conn: &Conn, propagate: bool, destination: A, event_mask: B, event: C) -> Result<VoidCookie<'_, Conn>, ConnectionError>
where
    Conn: RequestConnection + ?Sized,
    A: Into<Window>,
    B: Into<u32>,
    C: Into<[u8; 32]>,
{
    ...
}
```

**Comment by sandmor** [comment]
Yeah, looks good, but what I would put in the `response_type` and `sequence`?

**Comment by psychon** [comment]
From https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:SendEvent:

> The contents of the event are otherwise unaltered and unchecked by the server except to force on the most significant bit of the event code and to set the sequence number in the event correctly.

Thus, `sequence` can be whatever you want.

This also means that `response_type` must be set correctly to identify the event you want. There are constants for the events, e.g. `x11rb::protocol::xproto::KEY_PRESS_EVENT`:
```rust
/// Opcode for the KeyPress event
pub const KEY_PRESS_EVENT: u8 = 2;
```
(Also seen on https://docs.rs/x11rb/0.6.0/x11rb/protocol/xproto/constant.KEY_PRESS_EVENT.html)

None of the examples use the `SendEvent` request, but we have this in a test, at least:
https://github.com/psychon/x11rb/blob/30764e30995098e9b0a1888f730a276ba0c2098b/tests/multithread_test.rs#L30-L41

**Comment by sandmor** [comment]
Thank you, it works very well, no I only have to understand why my paste operation is broken...

**Comment by psychon** [comment]
> now I only have to understand why my paste operation is broken...

```diff
$ git diff                                                                              master:1
diff --git a/src/platform/linux/xcb/clipboard.rs b/src/platform/linux/xcb/clipboard.rs
index d651f6c..0d95e4d 100644
--- a/src/platform/linux/xcb/clipboard.rs
+++ b/src/platform/linux/xcb/clipboard.rs
@@ -27,6 +27,8 @@ fn load_from_clipboard_inner(conv_target: Atom) -> Result<Option<Vec<u8>>, OSErr
         XCB.atoms.CLIPBOARD_RECEIVER,
         CURRENT_TIME,
     )?;
+    use x11rb::connection::Connection;
+    XCB.conn.flush()?; // Actually send the above request
     let start = Instant::now();
     while Instant::now() < start + Duration::from_millis(5) {
         run_event_for_queue()?;
```
