### ISSUE TITLE
Support for WM extension atoms like `_NET_WM_NAME`

### ISSUE THREAD

**Issue by sassman** [psychon/x11rb#539]
I very appreciate the tutorial, it got me started quite well. 

My problem is fetching the window title under ubuntu. The following code yields an empty name:
```rust
#[cfg(test)]
mod test {
    use std::error::Error;

    use std::convert::TryInto;
    use x11rb::connection::{Connection, SequenceNumber};
    use x11rb::errors::{ConnectionError, ReplyError, ReplyOrIdError};
    use x11rb::protocol::xproto::*;
    use x11rb::protocol::Event;
    use x11rb::protocol::Request::MapWindow;
    use x11rb::wrapper::ConnectionExt as _;
    use x11rb::COPY_DEPTH_FROM_PARENT;

    #[test]
    fn should_fetch_winodw_names() -> anyhow::Result<()> {
        let (conn, screen_num) = x11rb::connect(None)?;
        let screen = &conn.setup().roots[screen_num];
        let win = screen.root;
        let tree = conn.query_tree(win)?.reply()?;
        for win in tree.children {
            let attr = conn.get_window_attributes(win)?.reply()?;

            if let MapState::Viewable = attr.map_state {
                let name = conn
                    .get_property(false, win, AtomEnum::WM_NAME, AtomEnum::STRING, 0, u32::MAX)?
                    .reply()?;
                let name = String::from_utf8(name.value)?;
                assert!(name.len() > 0, "A window has no name!");
            }
        }

        Ok(())
    }
}
```

However, after a bit of research the window title is either in property `WM_NAME` or in `_NET_WM_NAME` [like you can see here](https://github.com/dancor/wmctrl/blob/0181e8e4a7ed98255f6ef930875e56560f19aa95/main.c#L1436)

I'm not an X11 expert, so was not able to find the actual definitions of those `_NET` atom extension values. 
Maybe you know a way how to use them or find those definitions so that I could send a PR for extending the `AtomEnum` for all those `_NET` values?

The specs for those properties [can be found here](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#idm46018259898240)

**Comment by sassman** [comment]
A thing I also tried without success was:
```rust
                let wm_name_atom = conn.intern_atom(true, "_NET_WM_NAME".as_bytes())?.reply()?;
                let name = conn
                    .get_property(false, win, wm_name_atom.atom, AtomEnum::STRING, 0, u32::MAX)?
                    .reply()?;
                let name = String::from_utf8(name.value)?;
                dbg!(&name);  // still an empty string
```

**Comment by eduardosm** [comment]
>  Maybe you know a way how to use them or find those definitions so that I could send a PR for extending the `AtomEnum` for all those `_NET` values?

The `_NET_WM_NAME` atom does not have a predefined name, so you have to use `intern_atom`.



> ```rust
>                 let name = conn
>                     .get_property(false, win, wm_name_atom.atom, AtomEnum::STRING, 0, u32::MAX)?
>                     .reply()?;
> ```

`_NET_WM_NAME` properties usually have the `UTF8_STRING` type, not `STRING`, so you would have to do:

```rust
let wm_name_atom = conn.intern_atom(true, b"_NET_WM_NAME")?.reply()?;
let utf8_string_atom = conn.intern_atom(true, b"UTF8_STRING")?.reply()?;
let name = conn
    .get_property(false, win, wm_name_atom.atom, utf8_string_atom.atom, 0, u32::MAX)?
    .reply()?;
let name = String::from_utf8(name.value)?;
dbg!(&name);

**Comment by eduardosm** [comment]
> However, after a bit of research the window title is either in property `WM_NAME` or in `_NET_WM_NAME` [like you can see here](https://github.com/dancor/wmctrl/blob/0181e8e4a7ed98255f6ef930875e56560f19aa95/main.c#L1436)

To sum up:
`WM_NAME` is the legacy property, which may be a latin-1 string or a frankenstein-ish thing called compound text. `_NET_WM_NAME` is the newer property, which is an UTF8 string. You probably want to check first for the `_NET_WM_NAME` property and, if it is not set, fall back `WM_NAME`.

**Comment by psychon** [comment]
I quickly threw something together that works with both urxvt (`_NET_WM_NAME`) and xterm (`WM_NAME`, interpreted as utf8, which is incorrect, but works for ASCII):
```rust
use x11rb::protocol::xproto::ConnectionExt;

x11rb::atom_manager! {
    pub Atoms: AtomsCookie {
        _NET_WM_NAME,
        UTF8_STRING,
    }
}

fn try_print(string: &[u8]) -> Result<(), ()> {
    match std::str::from_utf8(&string) {
        Ok(string) => {
            println!("{}", string);
            Ok(())
        }
        Err(err) => {
            println!("{:?} ({:?})", string, err);
            Err(())
        }
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, _screen_num) = x11rb::connect(None)?;
    let atoms = Atoms::new(&conn)?.reply()?;
    let input = conn.get_input_focus()?.reply()?.focus;
    let prop = conn.get_property(
        false,
        input,
        atoms._NET_WM_NAME,
        atoms.UTF8_STRING,
        0,
        u32::MAX,
    )?.reply()?;
    if prop.type_ == x11rb::NONE || try_print(&prop.value).is_err() {
        let prop = conn.get_property(
            false,
            input,
            x11rb::protocol::xproto::AtomEnum::WM_NAME,
            x11rb::protocol::xproto::AtomEnum::STRING,
            0,
            u32::MAX,
        )?.reply()?;
        let _ = try_print(&prop.value);
    }
    Ok(())
}
```
Dunno if it is really worth it to use the `atom_manager!` macro here. Two `intern_atom` calls would work equally well, but this version does only one round trip for the atoms instead of two. ;-)

**Comment by sassman** [comment]
Thanks a lot, I learned newly about the `atom_manager` and the stuff works in general quite nice.

However, some windows on ubuntu misbehave and don't want to spit out any name, for instance `Terminal`. I'm currently investigating with different Linux distros and versions.

But I have the suspicion that the window hierarchy might be the problem, specifically I'm `query_tree` from the root window, and only focussing on `MapState::Viewable` windows. It might be that the viewable window is actually not the holder and owner of the title. But I'll keep you guys posted. For now many thanks.

**Comment by sassman** [comment]
Finally, I got it working, it was as suspected the window hierarchy. For the terminal there are (at least) 2 windows, one without a name that is seems like a root window and a subwindow that has the expected title. 

Just for the curious I will share the code:

```rust
pub fn get_visible_windows<C: ConnectionExt>(conn: &C, screen: &Screen) -> Result<Vec<Window>> {
    get_all_sub_windows(conn, &screen.root)
}

fn get_all_sub_windows<C: ConnectionExt>(conn: &C, root: &Window) -> Result<Vec<Window>> {
    let tree = conn.query_tree(*root)?.reply()?;
    let mut result = vec![];
    for window in tree.children {
        let attr = conn.get_window_attributes(window)?.reply()?;
        if let MapState::Viewable = attr.map_state {
            result.push(window);
        }
        let mut sub_windows = get_all_sub_windows(conn, &window)?;
        result.append(&mut sub_windows);
    }

    Ok(result)
}
```

Thanks again for your help and your project.
