### ISSUE TITLE
Incomplete example in the tutorial

### ISSUE THREAD

**Issue by SpyrosRoum** [psychon/x11rb#540]
Hello, I am going through the tutorial in the examples and I believe I found an unfinished code example [here](https://github.com/psychon/x11rb/blob/ea9b76d35e4955e225f736299d22495d02b972ce/examples/tutorial.rs#L1912)

I think a `?` is missing for the tree reply, and also this line for `trans`:
`let trans = conn.translate_coordinates(win, tree.parent, geom.x, geom.y)?.reply()?;`
I'd open a pull request my self but I'm not sure if I got the src and the dst windows & coordinates swapped.

**Comment by psychon** [comment]
This seems to be the equivalent section from the original libxcb tutorial: https://www.x.org/releases/X11R7.7/doc/libxcb/tutorial/index.html#wingetinfo
Apparently, someone (me) accidentally removed some part that should have stayed.

Anyway, just to make sure that I understand you correctly: Would you say the following patch fixes this issue?
```diff
diff --git a/examples/tutorial.rs b/examples/tutorial.rs
index 8c647ae..a64bd21 100644
--- a/examples/tutorial.rs
+++ b/examples/tutorial.rs
@@ -1894,7 +1894,6 @@ fn example_get_geometry<C: Connection>(conn: &C, win: Window) -> Result<(), Repl
 //
 // As usual, we need two functions to fill this structure:
 //
-//
 //    fn translate_coordinates(&self, src_window: u32, dst_window: u32, src_x: i16, src_y: i16)
 //    -> Result<Cookie<Self, TranslateCoordinatesReply>, ConnectionError>
 //
@@ -1907,7 +1906,8 @@ fn example_get_and_query<C: Connection>(conn: &C, win: Window) -> Result<(), Rep
     let geom = conn.get_geometry(win)?;
     let tree = conn.query_tree(win)?;
     let geom = geom.reply()?;
-    let tree = tree.reply();
+    let tree = tree.reply()?;
+    let trans = conn.translate_coordinates(win, tree.parent, geom.x, geom.y)?.reply()?;
 
     // the translated coordinates are in trans.dst_x and trans.dst_y
 
```

**Comment by SpyrosRoum** [comment]
I asked you because I wasn't sure what is considered the src and what the dst but if I you compare it with the original tutorial it seems to be the same as the line I wrote (or your diff). Assuming the order of the variables in your `translate_coordinates()` is the same as the xcb's, then this should be correct.

**Comment by psychon** [comment]
Ah, okay. https://docs.rs/x11rb/0.7.0/x11rb/protocol/xproto/fn.translate_coordinates.html can answer that. No idea if it makes sense here. :-)

> Assuming the order of the variables in your translate_coordinates() is the same as the xcb's, then this should be correct.

Yup, it is.

Do you still want to submit this as a PR?

**Comment by SpyrosRoum** [comment]
Sure, I can do that right now!

As a side note, it looks like you have done some great work with this library and the documentation of it. As someone who really wants to try and make a window manager, thanks you!

**Comment by psychon** [comment]
Thanks. Feel free to ask any questions. It's great that you mention the documentation. Usually, everything X11 is seen as arcane and badly documented (at least that's the impression I get from... everywhere?)
