### ISSUE TITLE
warp_pointer does not move the pointer

### ISSUE THREAD

**Issue by SpyrosRoum** [psychon/x11rb#546]
Okay, this is a bit of a weird issue I think.
I am using warp_pointer to move the pointer but it does not exactly works. If I print the position of the pointer it appears to be where I move it, but on the screen it doesn't actually move, it stays in the same place, and if I move it with the mouse and then print its locations, it prints the location that's visible on the screen.

Here is what I do: 
```rust
let (dst_x, dst_y) = (
    (window.width + self.config.border_width as u16 - 1) as i16,
    (window.height + self.config.border_width as u16 - 1) as i16,
);

self.conn.warp_pointer(x11rb::NONE, window.id, 0, 0, 0, 0, dst_x, dst_y);
```
This happens in a button press event. In a button release event I have the following:

```rust
dbg!(&event.root_x, &event.root_y);
```

If I press and release the button without moving the mouse at all, it prints the location of the bottom right corner of the window but the curosr on the screen has not moved. If I move the mouse before releasing the button it print the location that the mouse is on the screen.

Any ideas of why this might be happening?

**Comment by psychon** [comment]
Are you using Wayland / XWayland? I guess that one cannot warp the cursor there.

**Comment by psychon** [comment]
Quick example that seems to work fine here:
```rust
use x11rb::connection::Connection;
use x11rb::protocol::xproto::ConnectionExt as _;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];
    dbg!(conn.query_pointer(screen.root)?.reply()?);
    conn.warp_pointer(x11rb::NONE, screen.root, 0, 0, 0, 0, 50, 50)?;
    dbg!(conn.query_pointer(screen.root)?.reply()?);
    Ok(())
}
```
```
[src/main.rs:7] conn.query_pointer(screen.root)?.reply()? = QueryPointerReply {
    same_screen: true,
    sequence: 1,
    length: 0,
    root: 1889,
    child: 8389207,
    root_x: 2654,
    root_y: 588,
    win_x: 2654,
    win_y: 588,
    mask: 0,
}
[src/main.rs:9] conn.query_pointer(screen.root)?.reply()? = QueryPointerReply {
    same_screen: true,
    sequence: 3,
    length: 0,
    root: 1889,
    child: 8388713,
    root_x: 50,
    root_y: 50,
    win_x: 50,
    win_y: 50,
    mask: 0,
}
```

**Comment by SpyrosRoum** [comment]
I am not on Wayland/XWayland.
Your example does work..
I might have an idea. I am using Xephyr to test my wm, so is it possible that that's why it's not working?

**Comment by SpyrosRoum** [comment]
Actually no, dwm does the same thing and works fine in Xephyr :/

**Comment by SpyrosRoum** [comment]
I am not sure if I missed something in the past but now this works when run outside of Xephyr. It still doesn't actually wrap the pointer when running in Xephyr but I say that's good enough
