### ISSUE TITLE
RustConnection: Support LAUNCHD mode

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#552]
https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/10
(Not much time right now, but seems important in general)

**Comment by DemiMarie** [comment]
This fixes a security vulnerability (local privilege escalation) when used properly.

**Comment by psychon** [comment]
@DemiMarie What is the relation to the above-mentioned https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/10 and your https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/30 ? From a quick look, I would say that your the latter is a superset of the earlier one. Both allow specifying an absolute path in `$DISPLAY`, but yours also touches the parsing code a bit to make things better than "just enable what was available on macOS".

If I got this right, then I guess the issue is now rather about the latter MR (since that one was just merged (by me)).

**Comment by DemiMarie** [comment]
> @DemiMarie What is the relation to the above-mentioned https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/10 and your https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/30 ? From a quick look, I would say that your the latter is a superset of the earlier one. Both allow specifying an absolute path in `$DISPLAY`, but yours also touches the parsing code a bit to make things better than "just enable what was available on macOS".
> 
> If I got this right, then I guess the issue is now rather about the latter MR (since that one was just merged (by me)).

correct!
