### ISSUE TITLE
Shouldn't xproto::Atom and xproto::AtomEnum be conmparable?

### ISSUE THREAD

**Issue by SpyrosRoum** [psychon/x11rb#574]
I think it would be extremely useful to be able to directly compare the two, especially in match arms

**Comment by psychon** [comment]
Feel free to tell me how to structure the code to make it easier. Here is how things are currently:

An atom in X11 is an `u32`. Just a number. You ask the X11 server for "hey, please give me the `FoOBaR` atom" and it answers 12345. (This is the `InternAtom` request.) These atoms are represented as `Atom`, which is just a type alias for `u32` in x11rb.

Then the designers of X11 thought something like "atoms are used everywhere. There are lots of atoms which everyone will have to use. Let's just pre-define them. For example, atom 39 is always `WM_NAME`.
The XML description from xcb-proto represents these predefined atoms as an `<enum>`, so you get `AtomEnum` in x11rb. To turn one of the values of `AtomEnum` into a number, you can use the conversion impls, for example `impl From<AtomEnum> for u32` (remember from above: `Atom == 32`). Thus, you can just write `Atom::from(AtomEnum::WM_NAME)` for this conversion.
However, if you want, you can also still use `intern_atom()` to turn `"WM_NAME"` into a number and will get the same response (but will also do unnecessary I/O).

Does this help a bit?

For your question about `match`... uhm.... how can one match on numbers? I do not think Rust offers anything useful here. The best idea that I can come up with right now is basically an `if` and not a `match`:
```rust
fn test_if_equals(a: u32, b: u32) -> bool {
    match a {
        a if a == b => true,
        _ => false,
    }
}
```
(Yes, this code is better written as just `a == b`, but that is not the point. The point is to use a `match` to compare two numbers.)

Perhaps I misunderstood your question and you are instead asking for `AtomEnum` to implement `PartialEq<Atom>`...? Would that even help with `match`? I'm not sure if that is a good idea. I'd rather turn the `AtomEnum` value into an `Atom` and then compare those.

**Comment by SpyrosRoum** [comment]
I was thinking that either implementing `PartialEq<Atom>` or making the AtomEnum `repr(u32)` would work but it appears I am wrong. 
Matching would be convenient for the `PropertyNotify` event but since it's not that easy (if even possible) `if / else if` will have to do :)
