### ISSUE TITLE
Add a "no unsafe code"-mode

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#59]
Random idea: Add an `allow_unsafe` feature (that is enabled by default). When this feature is disabled, we `#![forbid(unsafe_code)]` and all the XCB-FFI code goes away.

**Comment by psychon** [comment]
This idea is blocked by `ExtensionInformation`:
https://github.com/psychon/x11rb/blob/c03d877437581c340b0a3de744cb77e6019a1fa1/src/connection.rs#L673-L682
This is a cache that, well, caches `QueryExtensionReply`s from the X11 server. This is append-only and cache entries are never discarded. Since they are also not modified, `ExtensionInformation` can hand out shared references to its content with the same lifetime as the `ExtensionInformation` struct itself. However, the borrow checker does not know that this cache is append-only, an `unsafe` block is necessary for "transmuting" the cache contents so that they get the right lifetime.

**Comment by dalcde** [comment]
Since `QueryExtensionReply` is only 11 bytes of data and implements `Copy`, why not just return a copied value?

**Comment by psychon** [comment]
@dalcde You rock. :-)
Thank you very much.
