### ISSUE TITLE
xcb_atom_enum_t definition location

### ISSUE THREAD

**Issue by Kyle-Thompson** [psychon/x11rb#603]
Rather than hardcoding numbers all over the place, I'd rather make use of some enums in `xproto.h` like `xcb_atom_enum_t`. I can't seem to find this anywhere in the project though.

**Comment by psychon** [comment]
Are you looking for atoms like this?
https://docs.rs/xcb/0.9.0/xcb/xproto/constant.ATOM_WM_CLASS.html

I'm not sure why the docs show these as constants in the xproto module. These are associated constants of the `AtomEnum` struct:
https://github.com/psychon/x11rb/blob/424ca2bc4aa0cfff628d5d420aa8cec6afa50fc1/src/protocol/xproto.rs#L3917-L3922
Here is a random example using such a constant:
https://github.com/psychon/x11rb/blob/424ca2bc4aa0cfff628d5d420aa8cec6afa50fc1/examples/simple_window.rs#L61-L68

**Comment by eduardosm** [comment]
> Are you looking for atoms like this?
> https://docs.rs/xcb/0.9.0/xcb/xproto/constant.ATOM_WM_CLASS.html
> 
> I'm not sure why the docs show these as constants in the xproto module. These are associated constants of the `AtomEnum` struct:

The docs are from another crate. I think you wanted to put this link:
https://docs.rs/x11rb/0.8.0/x11rb/protocol/xproto/struct.AtomEnum.html

**Comment by psychon** [comment]
:facepalm:

**Comment by Kyle-Thompson** [comment]
No, I'm looking for an equivalent to XCB_ATOM_ATOM like you see on line 1038 [here](https://xcb.freedesktop.org/manual/xproto_8h_source.html). As it stands I have to use magic numbers in place of these more descriptive values. Does the enum `xcb_atom_enum_t` (line 1032 of the same file) have an equivalent in this project?

**Comment by eduardosm** [comment]
That's exactly what [`AtomEnum`](https://docs.rs/x11rb/0.8.0/x11rb/protocol/xproto/struct.AtomEnum.html) provides. For the case of  `XCB_ATOM_ATOM`, you can use [`x11rb::protocol::xproto::AtomEnum::ATOM`](https://docs.rs/x11rb/0.8.0/x11rb/protocol/xproto/struct.AtomEnum.html#associatedconstant.ATOM).

**Comment by Kyle-Thompson** [comment]
Ah I see. It can be hard to search for these things when they've been renamed. Thanks for your help.
