### ISSUE TITLE
How to store the connection type?

### ISSUE THREAD

**Issue by Kyle-Thompson** [psychon/x11rb#604]
Sorry if this is a ridiculous question but I'm not sure how to deal with this. I'm writing a wrapper struct around x11rb so my app has a simple interface to whatever I need with X11. My issue however is that I can't seem to store the connection because it's type is opaque and not "object safe". I would really like to just do something like

```
struct XWrapper {
    conn: ??,
}

impl XWrapper {
    pub fn new() -> self {
        Self { conn: x11rb::connect(None).unwrap().0 }
    }
}
```
But this doesn't work for the reasons listed above. I must be missing something because it should not be this hard to just store a connection to the X server.

**Comment by psychon** [comment]
A quick first answer would be: Use `RustConnection` or `XcbConnection` directly.

A better answer seems to be the PR that @jDomantas just created. (Thanks for that already, I'm already looking into it. I'm not sure I would have come up with that idea myself.)

**Comment by psychon** [comment]
To make my last answer a bit more explicit:

- If you do not know if you want `RustConnection` or `XCBConnection`, I'd say "go with `RustConnection`" (it is implemented in pure Rust and 99% safe Rust).
- Your code sample would then be something like:
```
use x11rb::rust_connection::RustConnection;
struct XWrapper {
    conn: RustConnection,
}

impl XWrapper {
    pub fn new() -> Self {
        Self { conn: RustConnection::connect(None).unwrap().0 }
    }
}

**Comment by Kyle-Thompson** [comment]
I'll look into that, thanks.
