### ISSUE TITLE
can you please publish to creates.io to update the dependencies there :)

### ISSUE THREAD

**Issue by xMAC94x** [psychon/x11rb#607]
crates.io still has nix 0.19 dependencies

**Comment by psychon** [comment]
Sure, but I am curious: Why? Is `nix` somewhere in `x11rb`'s public API and that is causing mismatches for you? Or is this just about trimming your dependency tree (= `nix` only being built in one version instead of two)?

**Comment by xMAC94x** [comment]
Hi @psychon , its just for trimming our dependency tree, we (the veloren project) are having currently 5 different versions of nix, and every version is talking 15 secs for a clean compile (:
Thank you very much and have a nice day

**Comment by psychon** [comment]
Done.

Thanks for the info.
