### ISSUE TITLE
Odd behaviour of `convert_selection`

### ISSUE THREAD

**Issue by ArturKovacs** [psychon/x11rb#609]
I'm currently implementing an x11 clipboard, for [`arboard`](https://github.com/ArturKovacs/arboard) together with @daxpedda and we are experiencing a strange behavior that seems like it could be a bug. When sending a UTF-8 string to the clipboard manager and immediately trying to read the string back from the manager afterwards, the `SelectionNotify` sometimes comes back with the `property` set to 0 and no other useful message following. However if we wait 200 ms between sending the string and the `convert_selection` which tries to read it back, then it seems that it never fails. This behavior was observed on KDE 5.18 with the X11 windowing system.

For testing purposes we built a relatively small test program where this is demonstrated. See: https://github.com/ArturKovacs/smol-clip/blob/c3ce14ab6afba2463060f57aacee22693ea0430c/src/lib.rs#L98

Run `cargo run --example write` to reproduce the behaviour.

We've tried everything we could but no matter what we try something always fails or requires a very long wait, like shown above.

**Comment by psychon** [comment]
>  the SelectionNotify sometimes comes back with the property set to 0

Just in case you didn't know: 0 is `NONE`.

From https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#events:SelectionNotify:

> The owner of a selection should send this event to a requestor either when a selection has been converted and stored as a property or when a selection conversion could not be performed (indicated with property None).

And no, I do not know why this would fail, but at least the docs indicate what is going on, I think.

Well, since this is X11: Let's look at ICCCM!

From https://tronche.com/gui/x/icccm/sec-2.html#s-2.2:

> When a requestor wants the value of a selection, the owner receives a SelectionRequest event, which is defined as follows:
> [SNIP]
> The specified owner and selection will be the values that were specified in the SetSelectionOwner request. The owner should compare the timestamp with the period it has owned the selection and, if the time is outside, refuse the SelectionRequest by sending the requestor window a SelectionNotify event with the property set to None (by means of a SendEvent request with an empty event mask).

Sounds like your timestamp is outdated...? However, you are using `Time::CURRENT_TIME`. Dunno why this would cause an issue, but from ICCCM:

> Clients should not use CurrentTime for the time argument of a ConvertSelection request. Instead, they should use the timestamp of the event that caused the request to be made.

> This behavior was observed on KDE 5.18 with the X11 windowing system.

Are you saying that it only happens with KDE? I am using i3 and not running any clipboard manager. Should I still run your test program?

**Comment by psychon** [comment]
I ran your command under `xtrace` and, well, I don't have a clipboard manager running:
```
Setting selection owner to our window.
000:<:000a: 16: Request(22): SetSelectionOwner owner=0x02c00000 selection=0x1b9("CLIPBOARD") time=CurrentTime(0x00000000)
000:<:000b:  4: Request(43): GetInputFocus 
000:>:000b:32: Reply to GetInputFocus: revert-to=PointerRoot(0x01) focus=0x02800009
Asking the clipboard manager to request the data.
000:<:000c: 12: Request(19): DeleteProperty window=0x02c00000 property=0x249("_BOOP")
000:<:000d: 24: Request(24): ConvertSelection requestor=0x02c00000 selection=0x1f7("CLIPBOARD_MANAGER") target=0x1ff("SAVE_TARGETS") property=0x249("_BOOP") time=CurrentTime(0x00000000)
000:<:000e:  4: Request(43): GetInputFocus 
000:>:000e: Event SelectionNotify(31) time=CurrentTime(0x00000000) requestor=0x02c00000 selection=0x1f7("CLIPBOARD_MANAGER") target=0x1ff("SAVE_TARGETS") property=None(0x0)
000:>:000e:32: Reply to GetInputFocus: revert-to=PointerRoot(0x01) focus=0x02800009
000:<:000f:  8: Request(17): GetAtomName atom=0x1ff("SAVE_TARGETS")
000:>:000f:44: Reply to GetAtomName: name='SAVE_TARGETS'
SelectionNotify: 'SAVE_TARGETS'
successfully notified!
```
Since the `CLIPBOARD_MANAGER` selection is unowned, I guess the X11 server generates the `SelectionNotify` event with `property=None`. See https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:ConvertSelection.

**Comment by ArturKovacs** [comment]
Wow thanks for the in-depth answer!

> Just in case you didn't know: 0 is `NONE`.

Yep, I did not, thanks for pointing this out.

> And no, I do not know why this would fail, but at least the docs indicate what is going on, I think.

Well it at least indicates that this is pretty much certainly not a bug in `x11rb`.

> However, you are using `Time::CURRENT_TIME`.

Yeah, honestly I don't know what's the purpose of this argument and the ICCCM doesn't explain why is it any better to use anything other than the current time. Is it supposed to identify the event, so that the requestor can later match the corresponding `SelectionNotify`?

> I am using i3 and not running any clipboard manager

Oh, well this is a very important piece of information. We didn't even consider that a clipboard manager might not be present. Which more-or less invalidates this whole problem, as this means that we will have to implement serving the clipboard data, and in that case might as well just detect if the current application is the owner, and just return the data from the application-local variable directly.

**Comment by psychon** [comment]
> Yeah, honestly I don't know what's the purpose of this argument and the ICCCM doesn't explain why is it any better to use anything other than the current time. 

Yeah, I do not really know either. Using something else than `CurrentTime` can only lead to failed/rejected transfers...

> Well it at least indicates that this is pretty much certainly not a bug in x11rb.

Does this mean this issue can be closed? (But feel free to ask more questions here - I just can't promise much. Selection transfers are icky, especially once you discover `INCR` transfers for large data transfers.)

> We didn't even consider that a clipboard manager might not be present.

Welcome to X11 where everything gives you special cases ;-)

**Comment by ArturKovacs** [comment]
> Does this mean this issue can be closed?

Yep. I'm closing this.

> Selection transfers are icky, especially once you discover `INCR` transfers for large data transfers.

We are prepared for that. (At least I think we are :D)
