### ISSUE TITLE
EventMask should also Into<DeviceId>

### ISSUE THREAD

**Issue by incertia** [psychon/x11rb#632]
As per #554, `xi_query_device` and functions immediately using `DeviceId` have an `Into<DeviceId>` generic. However, `xinput_xi_select_events` takes in an `EventMask` parameter which contains a `DeviceId` and this requires a manual `.into()`.

On a completely unrelated note (although it is related to `EventMask`), we eventually need to turn `EventMask` into `Vec<u32>` to call `xi_select_events`. It would be kind of nice if bit fields could automatically `.into()` the correctly sized bitfield array. Currently we have to do something like
```rust
let event_mask = EventMask {
  deviceid: Device::ALL.into(),
  mask: [(XIEventMask::A | ... | XIEventMask::Z).into()].to_vec()
};
```
which is kind of uncool but it works I guess.

**Comment by psychon** [comment]
> However, xinput_xi_select_events takes in an EventMask parameter which contains a DeviceId and this requires a manual .into().

Uhm... so, how would you solve this? Right now the prototype is:
```rust
pub fn xi_select_events<'c, 'input, Conn>(conn: &'c Conn, window: xproto::Window, masks: &'input [EventMask]) -> Result<VoidCookie<'c, Conn>, ConnectionError>
where
    Conn: RequestConnection + ?Sized,
```
Do you want this to be changed to the following?
```rust
pub fn xi_select_events<'c, 'input, Conn, Mask>(conn: &'c Conn, window: xproto::Window, masks: &'input [Mask]) -> Result<VoidCookie<'c, Conn>, ConnectionError>
where
    Conn: RequestConnection + ?Sized,
   Mask: Into<EventMask>,
```
If so, then this would require to copy the `masks` slice into a `Vec` just for the conversion (`let masks = masks.iter().map(|x| x.into()).collect::<Vec<_>>()`). That's not really great and I think I'd prefer to avoid this unnecessary cost.

>  It would be kind of nice if bit fields could automatically .into() the correctly sized bitfield array. Currently we have to do something like

Sorry, I don't understand. What is a correctly sized bitfield array? The enum `XIEventMask` already implements conversion to `u8`, `u16` and `u32`.

The XML for `EventMask` is
```
    <struct name="EventMask">
        <field type="DeviceId" name="deviceid" altenum="Device" />
        <field type="CARD16"   name="mask_len" />
        <list type="CARD32" name="mask" mask="XIEventMask">
            <fieldref>mask_len</fieldref>
        </list>
    </struct>
```
This says that the list has elements of type `CARD32` which is exactly what we are generating. I guess one could do something with the `mask` attribute, but I am not quite sure what....

----

A bit unrelated, but why are you doing `mask: [(XIEventMask::A | ... | XIEventMask::Z).into()].to_vec()`? What's wrong with `vec![(XIEventMask::A | ... | XIEventMask::Z).into()]`?

**Comment by psychon** [comment]
I just re-read the title of this issue:

> EventMask should also Into<DeviceId>

Well... I guess you mean `XIEventMask` and not `EventMask`.

This is the definition of `DeviceId`:
```rust
pub type DeviceId = u16;
```
We have this implementation already:
```rust
impl From<XIEventMask> for u32 {
```
You are basically asking for `From<XIEventMask> for u16`. How would that impl work? `XIEventMask::BARRIER_LEAVE` is the largest value and has the value `1 << 26`. That does not fit into a `u16`, which is why that `impl` is not generated.

**Comment by incertia** [comment]
> Well... I guess you mean XIEventMask and not EventMask.

I am thinking of

```rust
struct x11rb::protocol::xinput::EventMask<D: Into<DeviceId>> {
  deviceid: D,
  // ...
}
```
So we can avoid the manual `<Device as Into<u16>>::into()` when assigning `Device::ALL` or `Device::ALL_MASTER` to the `deviceid` field of `xinput::EventMask`, much like when we pass `Device` to the `xinput::` set of functions that take in `Into<DeviceId>`, e.g.
```rust
pub fn xi_query_device<Conn: ?Sized, A>(
    conn: &Conn, 
    deviceid: A
) -> Result<Cookie<'_, Conn, XIQueryDeviceReply>, ConnectionError> 
where
    Conn: RequestConnection,
    A: Into<DeviceId>, 
```

It's not the biggest deal in the world but I am a fan of not having to write `.into()` whenever possible

> A bit unrelated, but why are you doing mask: [(XIEventMask::A | ... | XIEventMask::Z).into()].to_vec()? What's wrong with vec![(XIEventMask::A | ... | XIEventMask::Z).into()]?

Mostly just spaghetti code at the moment. both options are OK for the moment but this pattern *might* show up more than once within x11 (although I am not quite sure about that). Where you have a bitfield, which is passed to a function as an array of `uint8_t` or `uint32_t`, or whatever, and a size parameter for however many values are in the array. This could be XInput specific, for when they decide to add an additional 6 or more fields to `XIEventMask`, though.

**Comment by psychon** [comment]
```rust
struct x11rb::protocol::xinput::EventMask<D: Into<DeviceId>> {
  deviceid: D,
  // ...
}
```
Uhm. How would we know that the `deviceid` member needs special treatment? In the XML, it is just a normal field and it has type `DeviceId`:
```xml
    <struct name="EventMask">
        <field type="DeviceId" name="deviceid" altenum="Device" />
        <field type="CARD16"   name="mask_len" />
        <list type="CARD32" name="mask" mask="XIEventMask">
            <fieldref>mask_len</fieldref>
        </list>
    </struct>
```
Also, when receiving, we could only provide the "actual" type, i.e. `EventMask<DeviceId>` in your version.

The generated code is already huge and I don't think adding `Into`s everywhere helps with that. And it would also mean that the binary size becomes larger thanks to copies from monomorphisation.

Sorry, I am not convinced that this is a good idea.

**Comment by incertia** [comment]
makes sense. i'll close this for now.
