### ISSUE TITLE
Xft Support?

### ISSUE THREAD

**Issue by codic12** [psychon/x11rb#638]
Any way to draw antialiased text using x11rb? This is done on X11 usually with Xft, which doesn't work natively with non-Xlib libraries such as xcb (as it is a library not a protocol) so the X11 compatibility header has to be used for it; not sure how to do the equivalent with x11rb. Thanks.

**Comment by psychon** [comment]
> Any way to draw antialiased text using x11rb? 

Use Pango and cairo. For the "use cairo"-part, see https://github.com/psychon/x11rb/blob/master/cairo-example/src/main.rs.

> so the X11 compatibility header has to be used for it; not sure how to do the equivalent with x11rb.

Xft is a C library that only works with Xlib, so... there is nothing that we can do to support that directly.

Well, if you want to use Xlib, you can do so. I recently-ish saw some code example for that here (sorry, the branch is under active development and I cannot provide any permanent links): https://github.com/Smithay/smithay/pull/371/files

Relevant part (beware, I am quoting someone else's code; their copyright applies!):
```rust
pub struct XConnection {
[...]
    xlib_display: *mut x11_dl::xlib::Display,
    xcb_connection: XCBConnection,
}
[...]
        let (display, screen_number) = unsafe {
            let display = (xlib.XOpenDisplay)(ptr::null());

            if display.is_null() {
                return Err(ConnectToXError::XlibNoConnection);
            }

            (display, (xlib.XDefaultScreen)(display))
        };

        // Transfer ownership of the event queue to XCB since we use XCB to handle events.
        let xcb_connection_t = unsafe {
            let ptr = (xlib_xcb.XGetXCBConnection)(display);
            (xlib_xcb.XSetEventQueueOwner)(display, XEventQueueOwner::XCBOwnsEventQueue);
            ptr
        };

        let xcb_connection = unsafe {
            // Xlib implementation does not use XCB
            if xcb_connection_t.is_null() {
                (xlib.XCloseDisplay)(display);
                return Err(ConnectToXError::NoXlibXcb);
            }

            // Do not drop the connection upon closure since Xlib created the xcb_connection_t.
            // The Drop impl of `XConnection` will shutdown the Xlib Display
            XCBConnection::from_raw_xcb_connection(xcb_connection_t, false)
        };
```
Relevant part of their `Cargo.toml`:
```toml
x11rb = { version = "0.8.1", optional = true }
# We have to use a fork to get access to `XSetEventQueueOwner`
x11-dl = { git = "https://github.com/mendess/x11-rs", optional = true }
```
Does this help you?

**Comment by codic12** [comment]
Makes sense, I think I'll stick to Cairo; I don't want to pull in a dependency on XLib for simple font rendering.

Thank you for the detailed response and developing the library!
