### ISSUE TITLE
Even example code fails on WSL with an xserver running

### ISSUE THREAD

**Issue by JCBurnside** [psychon/x11rb#645]
I know this may seem a bit strange but I can't get even the simple_window example to run on WSL despite an xserver running and configured (I have a sample xcb project that runs just fine on it). it gives me `thread 'main' panicked at 'assertion failed: len <= mem::size_of::<sockaddr_un>()', /home/digital/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.22.2/src/sys/socket/mod.rs:1747:5` when I try to connect to the server with `x11rb::connect(None)?`.

**Comment by psychon** [comment]
First: [We actually test Windows support on CI](https://github.com/psychon/x11rb/blob/master/appveyor.yml), so I'd be surprised if it were this broken. (Hm, but appveyor is not linked from the readme... dunno whether that matters).

Next: `nix-0.22.2/src/sys/socket/mod.rs:1747:5` is this: https://github.com/nix-rust/nix/blob/124ed60877c52cb38ad5533815720a278e50876f/src/sys/socket/mod.rs#L1747

...but that doesn't really seem useful information... Uhm...

Oh, wait, you write WSL and not Windows. That's totally untested on our end. Still, that panic seems confusing. There is a `socketaddr` that is larger than the largest possible `sockaddr`? A backtrace for that would be useful, but I somehow feel like this would more likely be a bug in `nix`. But... dunno, a backtrace would help.

We only use `nix` in this file: https://github.com/psychon/x11rb/blob/master/src/rust_connection/stream.rs. There is a call to `nix::sendmsg`, one to `nix::poll`, and one to `nix::recvmsg`.

Looking at the code in `nix`, `socketaddr_storage_to_addr` is used by `read_mhdr`, `recvfrom`, `getpeername` and `getsockname`. `read_mhdr` is in turn used by `recvmsg` and `recvmmsg`.

The overlap between these two lists is `recvmsg`, so something must be going wrong there. But no idea what...

Random idea would be to get `strace` in WSL and figure out what exactly the `recvmsg` call that `nix` doesn't like is returning, then open an issue at https://github.com/nix-rust/nix/issues/new

Google only finds https://github.com/nix-rust/nix/issues/177 which is definitely something else.

**Comment by psychon** [comment]
Here is a simple example program that does not use x11rb and connects to an X11 server. Could you run this and see if it reproduces the problem? If so, that should be everything that is needed for a bug report to nix.
```rs
use std::net::TcpStream;
use std::os::unix::net::UnixStream;
use std::os::unix::io::{AsRawFd, RawFd};
use std::str::FromStr;
use nix::sys::socket::{recvmsg, sendmsg, MsgFlags};
use nix::sys::uio::IoVec;

// A X11 setup request
const TO_SEND: [u8; 12] = [
    0x6c, // Byte order: little endian
    0, 11, 0, 0, 0, // padding and protocol version
    0, 0, 0, 0, 0, 0, // We don't send any authorisation + padding
];

fn test_stream(fd: RawFd) -> Result<(), Box<dyn std::error::Error>> {
    let iov = [IoVec::from_slice(&TO_SEND[..])];
    sendmsg(fd, &iov, &[], MsgFlags::empty(), None)?;

    let mut buf = [0; 10];
    let mut cmsg = nix::cmsg_space!([RawFd; 16]);
    let result = recvmsg(fd, &[IoVec::from_mut_slice(&mut buf[..])], Some(&mut cmsg), MsgFlags::empty())?;
    println!("recvmsg() returned {:?}", result);
    Ok(())
}

fn try_tcp(display: u16) -> Result<(), Box<dyn std::error::Error>> {
    test_stream(TcpStream::connect(("localhost", 6000 + display))?.as_raw_fd())
}

fn try_unix(display: u16) -> Result<(), Box<dyn std::error::Error>> {
    let file = format!("/tmp/.X11-unix/X{}", display);
    test_stream(UnixStream::connect(file)?.as_raw_fd())
}

fn main() {
    // This should contain the value from the env:
    //   $ echo $DISPLAY
    //   :0
    let display = std::env::args().skip(1).next().as_ref().and_then(|s| u16::from_str(s).ok()).unwrap_or(0);
    println!("Connecting to DISPLAY=:{}", display);

    println!("unix: {:?}", try_unix(display));
    println!("tcp: {:?}", try_tcp(display));
}
```
When I just run this without any arguments (my X11 server does not listen on TCP):
```
Connecting to DISPLAY=:0
recvmsg() returned RecvMsg { bytes: 8, cmsghdr: None, address: Some(Unix(UnixAddr { sun: sockaddr_un { sun_family: 1 }, path_len: 18 })), flags: (empty), mhdr: msghdr { msg_name: 0x7ffd7c95c690, msg_namelen: 20, msg_iov: 0x7ffd7c95ce48, msg_iovlen: 1, msg_control: 0x56026045eae0, msg_controllen: 0, msg_flags: 0 } }
unix: Ok(())
tcp: Err(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
```
I ran `Xephyr -listen tcp :2` in another terminal and now run the above program with the command line argument `2`:
```
Connecting to DISPLAY=:2
recvmsg() returned RecvMsg { bytes: 10, cmsghdr: None, address: Some(Unix(UnixAddr { sun: sockaddr_un { sun_family: 1 }, path_len: 18 })), flags: (empty), mhdr: msghdr { msg_name: 0x7ffdc297fdc0, msg_namelen: 20, msg_iov: 0x7ffdc2980578, msg_iovlen: 1, msg_control: 0x5600fea94b20, msg_controllen: 0, msg_flags: 0 } }
unix: Ok(())
recvmsg() returned RecvMsg { bytes: 10, cmsghdr: None, address: None, flags: (empty), mhdr: msghdr { msg_name: 0x7ffdc297fe60, msg_namelen: 0, msg_iov: 0x7ffdc2980618, msg_iovlen: 1, msg_control: 0x5600fea94b20, msg_controllen: 0, msg_flags: 0 } }
tcp: Ok(())
```
For `Cargo.toml`, I just went with whatever `cargo init` produced and added `nix = "*"` to the `[dependencies]`.

**Comment by JCBurnside** [comment]
trying the same code no args i get
```
Connecting to DISPLAY=:0
unix: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
tcp: Err(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
```

**Comment by JCBurnside** [comment]
so guessing this is something wrong with my setup.  I didn't realize that x11rb just worked on windows as well.  How do you get an xserver running on windows?

**Comment by psychon** [comment]
> i get

Hm. Looks like "no x11 server running at `:0`". :-(

Does `echo $DISPLAY` print `:0` for you? Somehow this has to work for whatever you are trying with `x11rb::connect(None)?` to fail. It should use the same approach for connecting to the X11 server.

> How do you get an xserver running on windows?

No idea, sorry. For CI we use Cygwin to install xorg-server-extra, which contains Xvfb. This is an X11 server does not show anything visible on screen, so it is not really useful for actual use.

I think this also only works via TCP since there are no unix sockets on Windows without WSL...

**Comment by JCBurnside** [comment]
it prints nothing.  And dang I was hoping to not have to do this song and dance to get this to work.  My goal is to understand X11 to use it for a gui lib i am making that will be cross platform.  I don't have a linux machine set up hence the WSL option.   I also can't seem to figure out why the .bashrc doesn't get loaded when i launch my wsl.  But that isn't your problem.

**Comment by JCBurnside** [comment]
Ok small update.  manually setting DISPLAY to the address of the e-net adapter for WSL gets a compositor to work (tested with the program weston) how ever trying the code now results in 
```
Connecting to DISPLAY=:0
unix: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
thread 'main' panicked at 'unexpected address family 80', /home/digital/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.23.0/src/sys/socket/mod.rs:1878:15
```

**Comment by psychon** [comment]
Now I am really confused... we open a TcpStream and that results in an unknown address family? I.... am not really sure what to do about this, sorry.

> I don't have a linux machine set up hence the WSL option.

Would "try a Linux VM" help? I don't have a Windows machine to test with so... sorry.

**Comment by JCBurnside** [comment]
no worries i was considering setting one up anyway.  what's weird is this exact setup works with the xcb so maybe it is a nix issue.  i'll post over there.

**Comment by psychon** [comment]
You can try using `x11rb::xcb_ffi::XCBConnection::connect(None)` instead of `x11rb::connect(None)`. That should give you a libxcb-based connection.

**Comment by JCBurnside** [comment]
That worked! thank you.  I can now experiment properly!
