### ISSUE TITLE
Use #[must_use] for *Aux structs

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#652]
The newest clippy beta has lots of new complaints. The biggest one looks like this, but repeated quite often:
```
error: missing `#[must_use]` attribute on a method returning `Self`
    --> src/protocol/xproto.rs:5594:5
     |
5594 | /     pub fn background_pixmap<I>(mut self, value: I) -> Self where I: Into<Option<Pixmap>> {
5595 | |         self.background_pixmap = value.into();
5596 | |         self
5597 | |     }
     | |_____^
     |
     = note: `-D clippy::return-self-not-must-use` implied by `-D warnings`
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use
```
This actually seems like a good idea. All the `*Aux` structs have no side effects and only contain values. Thus, I think `#[must_use]` would be correct.

Only problem/fear is: I failed at figuring out when this attribute was stabilised. Does our current MSRV already have this?

**Comment by eduardosm** [comment]
> Only problem/fear is: I failed at figuring out when this attribute was stabilised. Does our current MSRV already have this?

`#[must_use]` is old enough, we shouldn't have any issue regarding MSRV.
