### ISSUE TITLE
Properly handle BOOL and BOOL32

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#66]
Issue #5 was about a BOOL that the python code from xcb-proto only tells us about as type uint8_t. I should write (and submit) a patch to xcb-proto to add something like a `xml_type` field that contains the original string for the type in the XML description. That way, it becomes possible to handle this correctly and turn it into `bool` in the Rust API.

**Comment by dalcde** [comment]
I assume this should be closed, but one possible enhancement on top of this is to use more descriptive type names, e.g. `WINDOW` instead of `u32`.

**Comment by psychon** [comment]
@dalcde Thanks! That's #13 and there already are things like e.g. `pub type WINDOW = u32;` in `xproto.rs`. Is this what you mean? Or do you mean "the generated code should use better type names"?

**Comment by dalcde** [comment]
Yeah I mean the generated code should use these type names when possible, so that the docs would be easier to understand.

**Comment by psychon** [comment]
After wasting way too much time on this, I finally noticed: Sorry, but xcbgen does not make the necessary information available. While parsing the XML, only the "resolved" types are preserved. So things like `<typedef oldname="CARD8" newname="KIND" />` and `<xidtype name="WINDOW" />` disappear in the Python types and I only get `CARD8` or `CARD32` (well, not even that, these types are helpfully mapped to C types).
The recent addition that allowed to handle `BOOL` specially only helped with problems in the mapping to C types (multiple types were mapped to `uint8_t`). But all the relevant type objects are still basically singletons and `<xidtype name="WINDOW" />` only gets the `CARD32` type from a type map and adds it to that map again under the name `WINDOW`. This means that `CARD32` and `WINDOW` can no longer be told about in the type objects...

Working around this limitation is possible (e.g. the XML describing a complex type's members is accessible under `.elt`, but this basically means re-handling the XML and trying to match this to the already parsed XML, which sounds complicated).

Sorry!
