### ISSUE TITLE
Could <enum> tags in XcbXml be enums in Rust?

### ISSUE THREAD

**Issue by notgull** [psychon/x11rb#682]
Right now, in `x11rb`, `enum`s in XcbXml are translated into newtype wrappers around their underlying type, with associated constants representing the enum items. In `breadx`, the way I was doing this was fitting the enum into one of three classes:

- If the enum has the same name as another type (for instance, the `Window` enum in `xproto`), just create an `impl` block that adds the associated constant to the original type.
- If the enum uses the `<bit>` option, it compiles into a [bitflags](https://github.com/bitflags/bitflags)-like structure, which I guess is what you do now for all enums.
- In other cases, the enum compiles into a real Rust enum, with an `repr(Int)` attribute and a list of items.

I was wondering whether or not my strategy was actually valid, so I consulted the X specification, but the closest thing I can find is [here](https://cgit.freedesktop.org/xcb/proto/plain/doc/xml-xcb.txt):

> The enum element represents an enumeration type, which can take on any of the values given by the contained item elements.

Does this mean that it will only ever consist of those elements, or does it mean that it *may* contain those elements?

**Comment by psychon** [comment]
> Does this mean that it will only ever consist of those elements, or does it mean that it may contain those elements?

Once upon a time, x11rb used "real" `enum`s. We changed to the newtype because of `ParsingError`s. See #545 (which links to three issues that it fixes). I think #458 is the most interesting one.

Does this answer this ticket? "We tried that and it broke".

**Comment by notgull** [comment]
It's always xinput, isn't it?

Given that it's only a few errant enums that ruin it for everyone else, I have to wonder if it wouldn't be worth it to do the GLX workaround thing and add a manual exception to those few enums.

**Comment by psychon** [comment]
Hm, dunno. Those are the cases that we know about. That's enough to make me worry about the cases that we do not know about. For that reason, I do not really want to play "what a mole" whenever a new cases come up. Oh and there are more implementations than just Xorg out there and other implementations might get more cases wrong.

So, yeah, for the library user it would be nicer if this were a real `enum`, but at least this way "the X11 server sending crap in fields that no one looks at" does not break the whole packet, but only "individual cases".

**Comment by notgull** [comment]
Fair enough. Newtypes are probably easier to serialize anyways.
