### ISSUE TITLE
Waiting for events on a RustConnection hangs

### ISSUE THREAD

**Issue by dtomvan** [psychon/x11rb#701]
This is either a bug, or I am not understanding how to handle a connection correctly.

Code:
```rust
pub struct Daemon {
    conn: RustConnection,
    root: u32,
}

impl Daemon {
    pub fn new() -> Result<Self> {
        let (conn, screen) = RustConnection::connect(None)
            .map_err(|e| eyre!("could not connect to X.org").with_error(|| e))?;

        let root = conn.setup().roots[screen].root;

        Ok(Self {
            conn,
            root,
        })
    }

    pub fn next_event(&self) -> Result<Event> {
        self.conn
            .wait_for_event()
            .with_context(|| "while trying to wait for the next event")
    }
}
```

`Daemon::next_event` hangs indefinitely.

**Comment by notgull** [comment]
Under normal circumstances, `wait_for_event` should never hang. I think we need context for the rest of the program. Do you have a window open? If so, is the window mapped? If so, do you have any event masks selected on the window?

**Comment by dtomvan** [comment]
I am not opening a window. I am trying to grab keys to bind them to a command, kind of like sxhkd. This minimal example is not grabbing any keys, though. It just connects to X.org by calling the `new` method. It stays in a loop, waiting for new events using `next_event`. Currently it just prints them out.

I am currently not on my pc, so I cannot send you my code right now. I’ll do that ASAP

**Comment by dtomvan** [comment]
My `main.rs`:
```rust
use color_eyre::Result;
use thkd::Daemon;

fn main() -> Result<()> {
    let mut daemon = Daemon::new()?;
    let event = daemon.next_event()?;
    eprintln!("{event:?}");

    Ok(())
}
```

**Comment by psychon** [comment]
Could you run `setxkbmap` while your program is running? That "almost surely" generates an event on all X11 connections. For example, `setxkbmap de` switches to a German keymap.

I guess what is happening is that you are not asking for any events and thus not getting any. And "wait for next event" obviously hangs when no next event arrives.

**Comment by MarcusGrass** [comment]
If you want to get key events from a window thaht you're not controlling you need to use xinput afaik. Here's an example of your code doing that, pardon my unwraps.

Using deps below.
```Toml
[package]
name = "any"
version = "0.1.0"
edition = "2021"

[dependencies]
x11rb = { version = "0.9.0", features = ["xinput"]}
x11-dl = { version = "2.19.1"}
```
And your modified code
```Rust
use x11rb::connection::Connection;
use x11rb::protocol::Event;
use x11rb::protocol::xinput::{DeviceId, DeviceUse};
use x11rb::protocol::xproto::{ChangeWindowAttributesAux, ConnectionExt, CreateWindowAux, EventMask, WindowClass};
use x11rb::rust_connection::RustConnection;

fn main() {
    let mut daemon = Daemon::new();
    let event = daemon.next_event();
    eprintln!("{event:?}");
}
pub struct Daemon {
    conn: RustConnection,
    root: u32,
}

impl Daemon {
    pub fn new() -> Self {
        let (conn, screen) = RustConnection::connect(None).unwrap();

        let screen = &conn.setup().roots[screen];
        let root = screen.root;

        // Get registered devices
        let devices = x11rb::protocol::xinput::list_input_devices(&conn).unwrap().reply().unwrap();
        for device in devices.devices {
            
            // Find keyboards
            if device.device_use == DeviceUse::IS_X_KEYBOARD {
                // I only have one keyboard plugged in and it's "openeded" but you might have more and need to
                // first run `x11rb::protocol::xinput::open_device(&conn, device.device_id).unwrap().reply().unwrap();`
                
                // Select events for the keyboards
                x11rb::protocol::xinput::xi_select_events(&conn, root, &[
                    x11rb::protocol::xinput::EventMask {
                        deviceid: device.device_id as u16,
                        // These are REALLY hard to find outside of c-macros,
                        // they exist as generated code in https://github.com/AltF02/x11-rs/blob/master/x11-dl/src/xinput2.rs
                        // If you add that as a dependency you can use these constants.
                        // I would just hardcode them if you don't need x11-dl as a dependency for something else
                        mask: vec![(x11_dl::xinput2::XI_RawKeyPressMask | x11_dl::xinput2::XI_RawKeyReleaseMask) as u32]
                    }
                ]).unwrap().check().unwrap();
            }
        }

        Self {
            conn,
            root,
        }
    }

    pub fn next_event(&self) -> Event {
        self.conn
            .wait_for_event()
            .unwrap()
    }
}
```
The underlying problem is that you're not listening to the relevant events. Since you don't have a window up you only get some meta-events about the state of the server, @psychon's suggestion gives an event but if you're looking for keypresses outside your window you need to go through a device and xinput.
I hope that helps!

**Comment by dtomvan** [comment]
> Could you run `setxkbmap` while your program is running? That "almost surely" generates an event on all X11 connections. For example, `setxkbmap de` switches to a German keymap.
> 
> I guess what is happening is that you are not asking for any events and thus not getting any. And "wait for next event" obviously hangs when no next event arrives.

I'll try this first, then I'll try doing the `x11-dl` solution.

**Comment by dtomvan** [comment]
I just got this:
```
MappingNotify(MappingNotifyEvent { response_type: 34, sequence: 0, request: KEYBOARD, fi
rst_keycode: 8, count: 248 })
MappingNotify(MappingNotifyEvent { response_type: 34, sequence: 0, request: MODIFIER, fi
rst_keycode: 0, count: 0 })
```

**Comment by dtomvan** [comment]
> ```rust
> XI_RawKeyPressMask
> ```

This works, thanks!
