### ISSUE TITLE
cairo example does not work

### ISSUE THREAD

**Issue by PaulDotSH** [psychon/x11rb#741]
Hi, the cairo example for me does not draw anything, it crates the transparent window but doesn't draw anything
Console output
```
MapNotify(MapNotifyEvent { response_type: 19, sequence: 26, event: 96468992, window: 96468992, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 26, window: 96468992, x: 0, y: 0, width: 100, height: 100, count: 0 }))
ConfigureNotify(ConfigureNotifyEvent { response_type: 150, sequence: 26, event: 96468992, window: 96468992, above_sibling: 0, x: 910, y: 479, width: 100, height: 100, border_width: 0, override_redirect: false }))
UnmapNotify(UnmapNotifyEvent { response_type: 18, sequence: 52, event: 96468992, window: 96468992, from_configure: false }))
Got an unknown event
MapNotify(MapNotifyEvent { response_type: 19, sequence: 52, event: 96468992, window: 96468992, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 52, window: 96468992, x: 0, y: 0, width: 100, height: 100, count: 0 }))
```

**Comment by psychon** [comment]
Uhm... okay... well, it definitely works for me. Are you using a composite manager (xcompmgr, picom, modern gnome, modern kde...)?

A quick debugging idea would be this:
```diff
diff --git a/cairo-example/src/main.rs b/cairo-example/src/main.rs
index d699b98..bac8a64 100644
--- a/cairo-example/src/main.rs
+++ b/cairo-example/src/main.rs
@@ -237,10 +237,12 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
     let atoms = AtomCollection::new(&conn)?.reply()?;
     let (mut width, mut height) = (100, 100);
     let (depth, visualid) = choose_visual(&conn, screen_num)?;
+    println!("Using visual {:x} with depth {}", visualid, depth);
 
     // Check if a composite manager is running. In a real application, we should also react to a
     // composite manager starting/stopping at runtime.
     let transparency = composite_manager_running(&conn, screen_num)?;
+    println!("Composite manager running: {:?}", transparency);
 
     let window = create_window(&conn, screen, &atoms, (width, height), depth, visualid)?;
 
```
For me, this says:
```
Using visual 7a with depth 32
Composite manager running: false
ReparentNotify(ReparentNotifyEvent { response_type: 21, sequence: 22, event: 52428800, window: 52428800, parent: 8388948, x: 0, y: 0, override_redirect: false }))
Got an unknown event
ConfigureNotify(ConfigureNotifyEvent { response_type: 22, sequence: 26, event: 52428800, window: 52428800, above_sibling: 0, x: 0, y: 0, width: 1920, height: 1043, border_width: 0, override_redirect: false }))
MapNotify(MapNotifyEvent { response_type: 19, sequence: 26, event: 52428800, window: 52428800, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 26, window: 52428800, x: 0, y: 0, width: 1920, height: 1043, count: 0 }))
ConfigureNotify(ConfigureNotifyEvent { response_type: 150, sequence: 26, event: 52428800, window: 52428800, above_sibling: 0, x: 1920, y: 37, width: 1920, height: 1043, border_width: 0, override_redirect: false }))
```
And visual 7a is:
```
$ xdpyinfo | grep -B 1 -A 6 -E 'visual id.*0x7a'
  visual:
    visual id:    0x7a
    class:    TrueColor
    depth:    32 planes
    available colormap entries:    256 per subfield
    red, green, blue masks:    0xff0000, 0xff00, 0xff
    significant bits in color specification:    8 bits
  visual:
```
I would guess that something goes with the "transparency stuff", so you could also try short-circuting `composite_manager_running`:
```diff
diff --git a/cairo-example/src/main.rs b/cairo-example/src/main.rs
index d699b98..f2706fe 100644
--- a/cairo-example/src/main.rs
+++ b/cairo-example/src/main.rs
@@ -240,7 +240,8 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
 
     // Check if a composite manager is running. In a real application, we should also react to a
     // composite manager starting/stopping at runtime.
-    let transparency = composite_manager_running(&conn, screen_num)?;
+    //let transparency = composite_manager_running(&conn, screen_num)?;
+    let transparency = false;
 
     let window = create_window(&conn, screen, &atoms, (width, height), depth, visualid)?;
 
```

**Comment by PaulDotSH** [comment]
First of all thanks a lot and sorry for the long comment you are about to read

```
Using visual 23 with depth 32
Composite manager running: false
MapNotify(MapNotifyEvent { response_type: 19, sequence: 26, event: 98566144, window: 98566144, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 26, window: 98566144, x: 0, y: 0, width: 100, height: 100, count: 0 }))
```

The thing is that when I don't use the compositor, everything works fine (well except transparency), but when I have the compositor enabled, even when I do
```
cr.set_source_rgba(0.9, 1.0, 0.9, 1.);
```
The window still isn't being drawn, I can see the window in the task bar, but I don't see anything drawn on the screen.

Setting the window to "keep above the others" in the task bar, will "prove" that the window is in the upper right corner, because I can't click anything "behind" the window, however nothing is being drawn, even though when hovering over the window it made in the task bar, it shows like it is rendered
![image](https://user-images.githubusercontent.com/84643540/182373590-6193180a-cde7-4bb3-825f-e66f165f743b.png)

Sadly you can't see the mouse, but in these 2 pictures, in the one with highlight and the "X" button, the mouse is more to the right, and in the other one, it is to the left, cairo-example's window blocking the input to go to my browser
![image](https://user-images.githubusercontent.com/84643540/182373760-f58eb9d1-a927-4256-aa90-20a2991b41d1.png)
![image](https://user-images.githubusercontent.com/84643540/182373780-7bfabf46-c7e8-418a-9fff-0858b66e3d5d.png)

So besides the problem that the window doesn't draw at all, also I need to have input "fall" through the window, when I have this overlay over a window, I should still be able to interact with the window under it

The DE I use is KDE.
Also running the ``xdpyinfo`` for both 23 and 7a outputs the exact same text as your output is.

Short-circuiting transparency has same output as not doing anything

**Comment by psychon** [comment]
Yay, X11 :-(

I.... have no good ideas. Here are some bad ones:

Instead of picking the first suitable visual, pick the last one (no idea why this should make a difference, but my X11 server has two apparently identical picture formats?!?):
```diff
diff --git a/cairo-example/src/main.rs b/cairo-example/src/main.rs
index d699b98..16790e8 100644
--- a/cairo-example/src/main.rs
+++ b/cairo-example/src/main.rs
@@ -90,10 +90,12 @@ fn choose_visual(conn: &impl Connection, screen_num: usize) -> Result<(u8, Visua
                 let d = info.direct;
                 (d.red_mask, d.green_mask, d.blue_mask, d.alpha_mask) == (0xff, 0xff, 0xff, 0xff)
             })
-            .find(|info| {
+            .filter(|info| {
                 let d = info.direct;
                 (d.red_shift, d.green_shift, d.blue_shift, d.alpha_shift) == (16, 8, 0, 24)
-            });
+            })
+            .inspect(|info| println!("Candidate picture format: {:?}", info))
+            .last();
         if let Some(format) = format {
             // Now we need to find the visual that corresponds to this format
             if let Some(visual) = formats.screens[screen_num]
```
How do I know about "two visuals": `xdpyinfo -ext RENDER` (this produces *lots* of output). The cairo-example program is looking for a picture format like this:
```
  pict format:
        format id:    0x25
        type:         Direct
        depth:        32
        alpha:        24 mask 0xff
        red:          16 mask 0xff
        green:         8 mask 0xff
        blue:          0 mask 0xff
```

> The DE I use is KDE.

I'm using i3 and no DE and no composite manager. Seems like I will need KDE for experimenting.

**Comment by PaulDotSH** [comment]
```
xdpyinfo -ext RENDE | grep "pict format"
```
returns nothing for me

After using the edits you provided, this is the output
```
Candidate picture format: Pictforminfo { id: 382, type_: DIRECT, depth: 32, direct: Directformat { red_shift: 16, red_mask: 255, green_shift: 8, green_mask: 255, blue_shift: 0, blue_mask: 255, alpha_shift: 24, alpha_mask: 255 }, colormap: 0 }
Using visual 23 with depth 32
Composite manager running: true
MapNotify(MapNotifyEvent { response_type: 19, sequence: 26, event: 127926272, window: 127926272, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 26, window: 127926272, x: 0, y: 0, width: 100, height: 100, count: 0 }))
Tansparency: true
ConfigureNotify(ConfigureNotifyEvent { response_type: 150, sequence: 26, event: 127926272, window: 127926272, above_sibling: 0, x: 910, y: 479, width: 100, height: 100, border_width: 0, override_redirect: false }))
Tansparency: true
UnmapNotify(UnmapNotifyEvent { response_type: 18, sequence: 52, event: 127926272, window: 127926272, from_configure: false }))
Got an unknown event
MapNotify(MapNotifyEvent { response_type: 19, sequence: 52, event: 127926272, window: 127926272, override_redirect: false }))
Got an unknown event
Expose(ExposeEvent { response_type: 12, sequence: 52, window: 127926272, x: 0, y: 0, width: 100, height: 100, count: 0 }))
Tansparency: true
ClientMessage(ClientMessageEvent { response_type: 161, format: 32, sequence: 59, window: 127926272, type_: 306, data: ClientMessageData([51, 1, 0, 0, 79, 65, 140, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) }))
Window was asked to close
```

Still the same problems

**Comment by eduardosm** [comment]
I think I figured it out
```
xwininfo: Window id: 0x6000000 "Simple Window"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 100
  Height: 100
  Depth: 32
  Visual: 0x7f
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -3740+0  -3740-980  +0-980
  -geometry 100x100+0+0
```

Check that `Colormap: 0x0`. After commenting `conn.free_colormap(colormap)` the example works. It looks like colormaps are not reference counted.

**Comment by psychon** [comment]
Argh. Thanks for that! From the docs for FreeColormap: https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:FreeColormap

> f the colormap is defined as the colormap for a window [...] the colormap for the window is changed to None,

Now, I do not really know why this makes a difference (the colormap is not used for anything). But whatever, if it works like that, it works like that..

**Comment by PaulDotSH** [comment]
Thanks a lot! However I still have a question/problem, is there any way we could make the mouse input "fall" through the window? i.e. clicking on a button on firefox that has this overlay over it still trigger the button?

**Comment by eduardosm** [comment]
> Thanks a lot! However I still have a question/problem, is there any way we could make the mouse input "fall" through the window? i.e. clicking on a button on firefox that has this overlay over it still trigger the button?

I think the [SHAPE extension](https://www.x.org/releases/X11R7.7/doc/xextproto/shape.html) allows to do that.

**Comment by psychon** [comment]
The example here does that: https://github.com/psychon/x11rb/issues/26

The important part is this:
```rust
    // Make the window click-through by setting an empty input shape
    conn.shape_rectangles(
        shape::SO::SET,
        shape::SK::INPUT,
        xproto::ClipOrdering::YX_BANDED,
        window,
        0,
        0,
        &[],
    )?;
```

**Comment by psychon** [comment]
https://github.com/psychon/x11rb/issues/26#issuecomment-1193134743 uses
```rust
use x11rb::protocol::shape::{self, ConnectionExt as _};
```
The `self`-part makes e.g. `shape::SO:SET` work. The `ConnectionExt` trait makes `conn.shape_rectangles()` work.

**Comment by PaulDotSH** [comment]
> [#26 (comment)](https://github.com/psychon/x11rb/issues/26#issuecomment-1193134743) uses
> 
> ```rust
> use x11rb::protocol::shape::{self, ConnectionExt as _};
> ```
> 
> The `self`-part makes e.g. `shape::SO:SET` work. The `ConnectionExt` trait makes `conn.shape_rectangles()` work.

That's weird, cargo won't build it
```
error[E0432]: unresolved imports `x11rb::protocol::shape`, `x11rb::protocol::shape`
  --> cairo-example/src/main.rs:18:22
   |
18 | use x11rb::protocol::shape::{self, ConnectionExt as _};
   |                      ^^^^^   ^^^^ no `shape` in `protocol`
   |                      |
   |                      could not find `shape` in `protocol`
```

**Comment by psychon** [comment]
You need to enable the `shape` feature of x11rb.

**Comment by PaulDotSH** [comment]
> You need to enable the `shape` feature of x11rb.

Oh right, now I get 
```
failed to resolve: could not find `ClipOrdering` in `xproto`
```
Sorry for wasting so much of your time, I tried to grep ClipOrdering and I cannot find where it is defined

**Comment by psychon** [comment]
https://docs.rs/x11rb/0.10.1/x11rb/?search=ClipOrdering says it is https://docs.rs/x11rb/0.10.1/x11rb/protocol/xproto/struct.ClipOrdering.html

**Comment by PaulDotSH** [comment]
> https://docs.rs/x11rb/0.10.1/x11rb/?search=ClipOrdering says it is https://docs.rs/x11rb/0.10.1/x11rb/protocol/xproto/struct.ClipOrdering.html

Ok now almost everything works, except clicking on the overlay brings the window inside it to focus, instead of keeping the overlay on top, is there any way to set the window "topmost", similar to windows?

**Comment by eduardosm** [comment]
> Ok now almost everything works, except clicking on the overlay brings the window inside it to focus, instead of keeping the overlay on top, is there any way to set the window "topmost", similar to windows?

You can add the `_NET_WM_STATE_ABOVE` value to the `_NET_WM_STATE` property (see https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html). You will need the [`intern_atom`](https://docs.rs/x11rb/latest/x11rb/protocol/xproto/fn.intern_atom.html) and [`change_prperty`](https://docs.rs/x11rb/latest/x11rb/wrapper/trait.ConnectionExt.html#method.change_property32) requests for that.
