### ISSUE TITLE
Should we bump the MSRV for OwnedFd?

### ISSUE THREAD

**Issue by notgull** [psychon/x11rb#750]
[Rust 1.63.0 was just released](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html), and the [`OwnedFd`](https://doc.rust-lang.org/std/os/unix/io/struct.OwnedFd.html) struct is now stable. Given that it essentially replaces the [`RawFdContainer`](https://docs.rs/x11rb-protocol/latest/x11rb_protocol/struct.RawFdContainer.html) type that we currently use, is it worth it to bump the MSRV to 1.63.0 in order to use it?

Pros:

- As the remainder of the Rust ecosystem (e.g. `nix`) evolves, it will likely used `BorrowedFd` and `OwnedFd` instead of `RawFd`. We don't want an ecosystem split
- We will no longer be responsible for the invariants of `RawFdContainer`, since it will be on the standard library's back.
- `OwnedFd` is niched, meaning that the layout of `OwnedFd` is optimized.
- Bumping the MSRV to 1.63.0 would mean we could use some of the features mentioned in #538 

Cons:

- Converting a `RawFd` to an `OwnedFd` requires `unsafe`, meaning that, unless `nix` also returns `OwnedFd` from its ancillary message function, we'd have to introduce `unsafe` code.
- Bumping the MSRV past 1.57.0 would mean that `x11rb` would not build with the version of `rustc` currently in the Ubuntu package repository.

**Comment by ids1024** [comment]
Looks like https://packages.debian.org/bookworm/rustc has 1.63 now. But it's also possible to use the `io-lifetimes` crate to support older versions, which some libraries that don't want to require 1.63 are doing.

`winit` (and `softbuffer`) is targetting 1.60.0 currently, so if it will be using x11rb (https://github.com/rust-windowing/winit/pull/2614), it's best for x11rb to not require a newer version, unless that is bumped soon.

**Comment by psychon** [comment]
> But it's also possible to use the io-lifetimes crate to support older versions

Oh, wow. I like that idea and went ahead and implemented it. However.... thanks to `FromRawFd::from_raw_fd` being unsafe, this breaks the crate (`#![cfg_attr(not(feature = "allow-unsafe-code"), forbid(unsafe_code))]`). `x11rb::rust_connection::Stream` currently implements FD-passing and abstract socket support thanks to `nix` making all necessary ingredients safe. That doesn't seem possible anymore with io-lifetimes.

I pushed my work to https://github.com/psychon/x11rb/tree/owned-fd.

**Comment by notgull** [comment]
I've been trying to get `sendmsg`/`recvmsg` into `rustix`, see bytecodealliance/rustix#505. `rustix` uses `io-lifetimes` by default, which would circumvent this issue.

**Comment by psychon** [comment]
Closed by #815
