### ISSUE TITLE
MSRV build broken due to once_cell v1.15

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#756]
A new Rust release means that some new clippy complaints from the clippy beta will show up, so I re-triggered the latest build. The latest successful action run used once_cell v1.14.0. The newest run failed in the msrv check with a newer version:

```
Downloading crates ...
  Downloaded once_cell v1.15.0
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.15.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

See https://github.com/matklad/once_cell/issues/201

**Comment by notgull** [comment]
There are three real options here:

- Bump the MSRV to 1.56
- Pin `once_cell` to 1.14
- Create a `Cargo.lock.MSRV` that uses 1.14 for MSRV tests and 1.15 for everything else

Personally I'd prefer the 1st option. Many crates (notable `libc`) are planning bumps to a 1.5x version in the near future, so we might as well bump now.

**Comment by psychon** [comment]
The first two options are fine with me, but the third one sounds complicated and https://github.com/smol-rs/async-io/issues/93#issuecomment-1255793764 says that it is hard to use/do.
