### ISSUE TITLE
Time for a new release!

### ISSUE THREAD

**Issue by rowan-sl** [psychon/x11rb#763]
The link to the examples for x11rb ([here](https://github.com/psychon/x11rb/blob/33a438c93c3cbf7dc2b25bbc2f4b726b800c3117/x11rb/src/lib.rs#L74)) is outdated (should be `/x11rb/examples` I think?)

**Comment by psychon** [comment]
Sorry, what? Your link points to a code line that already points to `/x11rb/examples`, doesn't it?

https://github.com/psychon/x11rb/blob/33a438c93c3cbf7dc2b25bbc2f4b726b800c3117/x11rb/src/lib.rs#L74

That exact link was fixed in July in commit ed59f94a4089fc93b16a4310a90c47e996490807. Am I missing something?

**Comment by rowan-sl** [comment]
oh sorry, looks like the latest version on [docs.rs](https://docs.rs/x11rb/0.10.1/x11rb/index.html) is from before that commit.

**Comment by psychon** [comment]
Hm, I guess this should be taken as a request for a new release then.

Anyone against this? Does anyone have time to look into this? From a quick look, I am not sure whether the next release should be v0.10.2 or v0.11. Does e.g.  7d1500b2eb74214431fe9209fbd0dc12a42c31e1 break anything semver-wise?

@notgull @eduardosm

**Comment by notgull** [comment]
I don't think anything is broken, so it can be another v0.10 release.

**Comment by psychon** [comment]
https://github.com/psychon/x11rb/commit/cbf53b16fc57334f74a54c5a9423c4ad14ab53a7 removes e.g. `impl From<CW> for u16` in `xproto.rs`. That's quite semver incompatible. :-(

**Comment by notgull** [comment]
Unfortunate :-( v0.11 it is

**Comment by eduardosm** [comment]
I'm a bit late, but... I believe it is time for a new release.

**Comment by psychon** [comment]
Aaaand... it's done.
