### ISSUE TITLE
Add a way to construct ClientMessageData

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#77]
Currently, the only way to construct a ClientMessageData is `TryParse`. That is really not meant to be user-facing API. I guess this needs something like `from_data32` etc.

It would be even better to have something like `fn construct_client_message32(window: WINDOW, type_: ATOM, data: [u32; 5]) -> ClientMessageEvent`. This should be able to set all the fields correctly and make using this a lot simpler...

**Comment by dalcde** [comment]
In general for `union X { Y, Z, ... }`, one ought to `impl From<Y> for X`

**Comment by psychon** [comment]
Thanks for the suggestion, that seems like a good idea.
