### ISSUE TITLE
put_image on x11rb-async

### ISSUE THREAD

**Issue by serpilliere** [psychon/x11rb#810]
Hi!

I am porting Sanzu (https://github.com/cea-sec/sanzu/tree/main/sanzu) to an async version.
The original code uses x11rb (which is great!) and it seems you merged the x11rb-async recently.

I face a problem regarding `put_image` on x11rb-async which seems not be ok on the x11rb without async.
Here is the problem:
It seems that in the async version, the `put_image` request does not reach the x server.

Using the main x11rb I made a simple example which does works:
```rust
            let size = window_size.0 as usize * window_size.1 as usize * 4;
            let mut img = vec![0x80u8; size];

            conn.put_image(
                ImageFormat::Z_PIXMAP,
                win_id,
                black_gc,
                window_size.0, window_size.1,
                0, 0,
                0,
                24,
                &img
            ).expect("Err in put image");
            conn.flush().unwrap();
```

If I run it x11rb through xtrace, I can see the request to the x server:
```
client (63): PutImage(PutImageRequest { format: Z_PIXMAP, drawable: 117440512, gc: 117440514, width: 100, height: 100, dst_x: 0, dst_y: 0, left_pad: 0, depth: 24, data: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128 ...
```

I did the very same code using the x11rb-async:
```rust
                        let size = width as usize * height as usize * 4;
                        let mut img = vec![0x80u8; size];

                        conn.put_image(
                            ImageFormat::Z_PIXMAP,
                            window,
                            black_gc,
                            width, height,
                            0, 0,
                            0,
                            24,
                            &img
                        ).await.expect("Err in put image");
                        conn.flush().await?;
```

But I don't see the `put_image` on xtrace.
I added another call to a working function in order to be sure I debug properly using trace:
```rust
                        let size = width as usize * height as usize * 4;
                        let mut img = vec![0x80u8; size];

                        conn.put_image(
                            ImageFormat::Z_PIXMAP,
                            window,
                            black_gc,
                            width, height,
                            0, 0,
                            0,
                            24,
                            &img
                        ).await.expect("Err in put image");
                        conn.flush().await?;

                        conn.poly_fill_rectangle(
                            window,
                            gc_id,
                            &[Rectangle {
                                x: 10,
                                y: 10,
                                width: 10,
                                height: 10,
                            }],
                        )
                        .await?;
```

And I see the trace in xtrace:
```

client (170): PolyFillRectangle(PolyFillRectangleRequest { drawable: 117440512, gc: 117440513, rectangles: [Rectangle { x: 10, y: 10, width: 10, height: 10 }] })
client (171): PolyFillRectangle(PolyFillRectangleRequest { drawable: 117440512, gc: 117440513, rectangles: [Rectangle { x: 10, y: 10, width: 10, height: 10 }] })
client (172): PolyFillRectangle(PolyFillRectangleRequest { drawable: 117440512, gc: 117440513, rectangles: [Rectangle { x: 10, y: 10, width: 10, height: 10 }] })
client (173): PolyFillRectangle(PolyFillRectangleRequest { drawable: 117440512, gc: 117440513, rectangles: [Rectangle { x: 10, y: 10, width: 10, height: 10 }] })
...
```

To see the serialized arguments sent trhough the `put_image` I added a log to the async version of `put_image`
```rust
pub async fn put_image<'c, 'input, Conn>(conn: &'c Conn, format: ImageFormat, drawable: Drawable, gc: Gcontext, width: u16, height: u16, dst_x: i16, dst_y: i16, left_pad: u8, depth: u8, data: &'input [u8]) -> Result<VoidCookie<'c, Conn>, ConnectionError>
where
    Conn: RequestConnection + ?Sized,
{
    println!("put_image!");
    let request0 = PutImageRequest {
        format,
        drawable,
        gc,
        width,
        height,
        dst_x,
        dst_y,
        left_pad,
        depth,
        data: Cow::Borrowed(data),
    };
    let (bytes, fds) = request0.serialize();
    println!("bytes {:?}", bytes);
    let slices = bytes.iter().map(|b| IoSlice::new(b)).collect::<Vec<_>>();
    conn.send_request_without_reply(&slices, fds).await
}
```

And I get:
```
put_image!
bytes [[72, 2, 22, 39, 0, 0, 0, 7, 3, 0, 0, 7, 100, 0, 100, 0, 0, 0, 0, 0, 0, 24, 0, 0], [128, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, ...
```
but no calls to `put_image` present on xtrace
Also note that the polygons are displayed: I based my test case on the example provided in the x11rb-async `xclock_utc.rs`

Did I miss something?

(I can provide the full test code)

**Comment by serpilliere** [comment]
Yes of course!
I tried to minimize the code (but maybe some stuffs can be still removed)
First, here is the code for the original test, on x11rb:
```rust
// This is (quite loosely) based on the original xeyes

extern crate x11rb;

use x11rb::connection::{Connection};
use x11rb::errors::{ReplyOrIdError};
use x11rb::protocol::xproto::*;
use x11rb::protocol::Event;
use x11rb::wrapper::ConnectionExt as _;
use x11rb::COPY_DEPTH_FROM_PARENT;

fn setup_window<C: Connection>(
    conn: &C,
    screen: &Screen,
    window_size: (u16, u16),
    wm_protocols: Atom,
    wm_delete_window: Atom,
) -> Result<Window, ReplyOrIdError> {
    let win_id = conn.generate_id()?;
    let win_aux = CreateWindowAux::new()
        .event_mask(EventMask::EXPOSURE | EventMask::STRUCTURE_NOTIFY | EventMask::POINTER_MOTION)
        .background_pixel(screen.white_pixel);

    conn.create_window(
        COPY_DEPTH_FROM_PARENT,
        win_id,
        screen.root,
        0,
        0,
        window_size.0,
        window_size.1,
        0,
        WindowClass::INPUT_OUTPUT,
        0,
        &win_aux,
    )?;

    let title = "xeyes";
    conn.change_property8(
        PropMode::REPLACE,
        win_id,
        AtomEnum::WM_NAME,
        AtomEnum::STRING,
        title.as_bytes(),
    )
    .unwrap();
    conn.change_property32(
        PropMode::REPLACE,
        win_id,
        wm_protocols,
        AtomEnum::ATOM,
        &[wm_delete_window],
    )
    .unwrap();

    conn.map_window(win_id).unwrap();

    Ok(win_id)
}

fn create_gc_with_foreground<C: Connection>(
    conn: &C,
    win_id: Window,
    foreground: u32,
) -> Result<Gcontext, ReplyOrIdError> {
    let gc = conn.generate_id()?;
    let gc_aux = CreateGCAux::new()
        .graphics_exposures(0)
        .foreground(foreground);
    conn.create_gc(gc, win_id, &gc_aux)?;
    Ok(gc)
}

fn main() {
    let (conn, screen_num) = x11rb::connect(None).expect("Failed to connect to the X11 server");

    let screen = &conn.setup().roots[screen_num];

    let wm_protocols = conn.intern_atom(false, b"WM_PROTOCOLS").unwrap();
    let wm_delete_window = conn.intern_atom(false, b"WM_DELETE_WINDOW").unwrap();

    let window_size = (100, 100);
    let (wm_protocols, wm_delete_window) = (
        wm_protocols.reply().unwrap().atom,
        wm_delete_window.reply().unwrap().atom,
    );
    let win_id = setup_window(&conn, screen, window_size, wm_protocols, wm_delete_window).unwrap();

    let black_gc = create_gc_with_foreground(&conn, win_id, screen.black_pixel).unwrap();

    conn.flush().unwrap();

    let mut need_repaint = false;

    let mut count = 0;
    loop {
        count += 1;
        let event = conn.wait_for_event().unwrap();
        let mut event_option = Some(event);
        while let Some(event) = event_option {
            match event {
                Event::Expose(event) => {
                    if event.count == 0 {
                        need_repaint = true;
                    }
                }
                Event::MotionNotify(_event) => {
                    need_repaint = true;
                }
                Event::ClientMessage(event) => {
                    let data = event.data.as_data32();
                    if event.format == 32 && event.window == win_id && data[0] == wm_delete_window {
                        println!("Window was asked to close");
                        return;
                    }
                }
                Event::Error(error) => {
                    println!("Unknown error {:?}", error);
                }
                event => {
                    println!("Unknown event {:?}", event);
                }
            }

            event_option = conn.poll_for_event().unwrap();
        }

        if need_repaint {
            // Create pixels

            let size = window_size.0 as usize * window_size.1 as usize * 4;
            let mut img = vec![0x80u8; size];
            for i in count..count + 20 {
                for j in 0..20 {
                    img[(j as usize*window_size.0 as usize + i as usize) * 4] = 0xFF;
                }
            }
            conn.put_image(
                ImageFormat::Z_PIXMAP,
                win_id,
                black_gc,
                window_size.0, window_size.1,
                0, 0,
                0,
                24,
                &img
            ).expect("Err in put image");
            conn.flush().unwrap();
            need_repaint = false;
        }
    }
}
```

with its cargo.toml
```toml
[package]
name = "test_img_x11rb"
version = "0.1.0"
authors = ["Fabrice Desclaux <fabrice.desclaux@cea.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
libc = "0.2"
log = "0.4.13"
spin_sleep = "0.3.7"

[dependencies.x11rb]
version = "0.8.0"
features = ["shm", "xtest", "xfixes", "damage"]
```

And here is the code for the x11Rb async version:
```rust
// This code is dual licensed under MIT OR Apache 2.0.

//! An implementation of the "XClock" example from `x11rb`, but using `x11rb-async`.

use async_executor::LocalExecutor;
use async_io::Timer;
use futures_lite::prelude::*;

use std::cell::RefCell;
use std::env;
use std::time::{Duration};

use x11rb_async::connection::Connection;
use x11rb_async::errors::{ConnectionError, ReplyOrIdError};
use x11rb_async::protocol::{xproto::*, Event};
use x11rb_async::rust_connection::RustConnection;



async fn create_gc_with_foreground<C: Connection>(
    conn: &C,
    win_id: Window,
    foreground: u32,
) -> Result<Gcontext, ReplyOrIdError> {
    let gc = conn.generate_id().await?;
    let gc_aux = CreateGCAux::new()
        .graphics_exposures(0)
        .foreground(foreground);
    conn.create_gc(gc, win_id, &gc_aux).await?;
    Ok(gc)
}

struct Atoms {
    utf8_string: Atom,
    wm_protocols: Atom,
    wm_delete_window: Atom,
    wm_name: Atom,
}

impl Atoms {
    async fn load(conn: &impl Connection) -> Result<Self, ReplyOrIdError> {
        let utf8_string = conn.intern_atom(false, b"UTF8_STRING").await?;
        let wm_protocols = conn.intern_atom(false, b"WM_PROTOCOLS").await?;
        let wm_delete_window = conn.intern_atom(false, b"WM_DELETE_WINDOW").await?;
        let wm_name = conn.intern_atom(false, b"WM_NAME").await?;

        let utf8_string = utf8_string.reply().await?.atom;
        let wm_protocols = wm_protocols.reply().await?.atom;
        let wm_delete_window = wm_delete_window.reply().await?.atom;
        let wm_name = wm_name.reply().await?.atom;

        Ok(Self {
            utf8_string,
            wm_protocols,
            wm_delete_window,
            wm_name,
        })
    }
}

async fn create_window(
    conn: &impl Connection,
    screen: &Screen,
    atoms: &Atoms,
    (width, height): (u16, u16),
) -> Result<Window, ReplyOrIdError> {
    // Create the window.
    let win_id = conn.generate_id().await?;
    let win_aux =
        CreateWindowAux::new().event_mask(EventMask::EXPOSURE | EventMask::STRUCTURE_NOTIFY);

    conn.create_window(
        screen.root_depth,
        win_id,
        screen.root,
        0,
        0,
        width,
        height,
        0,
        WindowClass::INPUT_OUTPUT,
        0,
        &win_aux,
    )
    .await?;

    let title = "xclock (async redox)";
    conn.change_property(
        PropMode::REPLACE,
        win_id,
        AtomEnum::WM_NAME,
        AtomEnum::STRING,
        8,
        title.len() as _,
        title.as_bytes(),
    )
    .await?;
    conn.change_property(
        PropMode::REPLACE,
        win_id,
        atoms.wm_name,
        atoms.utf8_string,
        8,
        title.len() as _,
        title.as_bytes(),
    )
    .await?;
    conn.change_property(
        PropMode::REPLACE,
        win_id,
        atoms.wm_protocols,
        AtomEnum::ATOM,
        32,
        1,
        &atoms.wm_delete_window.to_ne_bytes(),
    )
    .await?;

    conn.map_window(win_id).await?;

    Ok(win_id)
}

async fn main2() -> Result<(), Box<dyn std::error::Error>> {
    // This is shared between tasks.
    let (width, height) = (100, 100);
    let size = RefCell::new((width, height));

    // Open a new connection.
    let (conn, screen_index, drive) = RustConnection::connect(None).await?;
    let screen = conn.setup().roots.get(screen_index).unwrap();

    // Create an executor for spawning tasks.
    let ex = LocalExecutor::new();

    ex.run({
        let ex = &ex;
        let size = &size;
        let conn = &conn;

        async move {
            // Spawn a task to poll for events.
            let driver = ex.spawn(async move {
                if let Err(e) = drive.await {
                    eprintln!("Error while driving the connection: {}", e);
                }
            });

            // On X11RB_EXAMPLE_TIMEOUT, exit after a set timeout.
            if let Some(timeout) = env::var("X11RB_EXAMPLE_TIMEOUT")
                .ok()
                .and_then(|s| s.parse().ok())
            {
                ex.spawn(async move {
                    Timer::after(Duration::from_secs(timeout)).await;
                    eprintln!("Cancelling drive task due to $X11RB_EXAMPLE_TIMEOUT");
                    driver.cancel().await;
                })
                .detach();
            } else {
                driver.detach();
            }

            // Setup atoms for this connection.
            let atoms = Atoms::load(conn).await?;

            // Create a window.
            let window = create_window(conn, screen, &atoms, (width, height)).await?;

            // Create a graphics context.
            let gc_id = conn.generate_id().await?;
            conn.create_gc(gc_id, window, &CreateGCAux::new()).await?;



            let black_gc = create_gc_with_foreground(conn, window, screen.black_pixel).await.unwrap();



            // Span a task that redraws the window every second.
            ex.spawn(async move {
                // Create a timer that fires every second.
                let timer = Timer::interval(Duration::from_millis(10));
                let mut count = 0;
                // Iterate over this timer endlessly.
                timer
                    .then(move |_| async move {
                        // Redraw after one second has passed.
                        let (width, height) = *size.borrow();
                        println!("Update {}x{}", width, height);

                        let size = width as usize * height as usize * 4;
                        let mut img = vec![0x80u8; size];
                        count += 1;
                        for i in count..count + 20 {
                            for j in 0..20 {
                                img[(j as usize*width as usize + i as usize) * 4] = 0xFF;
                            }
                        }
                        conn.put_image(
                            ImageFormat::Z_PIXMAP,
                            window,
                            black_gc,
                            width, height,
                            0, 0,
                            0,
                            24,
                            &img
                        ).await.expect("Err in put image");
                        conn.flush().await?;


                        println!("Update ok");

                        Ok::<_, ConnectionError>(())
                    })
                    .for_each(|res| {
                        if let Err(e) = res {
                            eprintln!("Timer task failed: {}", e);
                        }
                    })
                    .await;
            })
            .detach();

            // Flush the connection so far.
            conn.flush().await?;

            loop {
                // Get the next event.
                let event = conn.wait_for_event().await?;

                println!("{:?}", event);

                match event {
                    Event::ConfigureNotify(cme) => {
                        // The window was resized.
                        *size.borrow_mut() = (cme.width, cme.height);
                    }

                    Event::ClientMessage(cme) => {
                        let data = cme.data.as_data32();

                        if cme.format == 32
                            && cme.window == window
                            && data[0] == atoms.wm_delete_window
                        {
                            println!("Window was asked to close");
                            return Ok::<_, Box<dyn std::error::Error>>(());
                        }
                    }

                    Event::Error(_) => println!("Unexpected error"),

                    _ => println!("Unhandled event"),
                }

                conn.flush().await?;
            }
        }
    })
    .await?;

    Ok(())
}

fn main() {
    if let Err(e) = async_io::block_on(main2()) {
        eprintln!("Fatal Error: {}", e);
    }
}

```
Thank you for your help!

**Comment by psychon** [comment]
@notgull Could you think about the following for a bit? I am not sure what I am doing here / stared at this for long enough that I am now confused.

```diff
diff --git a/x11rb-async/src/rust_connection/write_buffer.rs b/x11rb-async/src/rust_connection/write_buffer.rs
index 7fa63e0..ae49382 100644
--- a/x11rb-async/src/rust_connection/write_buffer.rs
+++ b/x11rb-async/src/rust_connection/write_buffer.rs
@@ -156,7 +156,7 @@ impl WriteBufferInner {
         // Otherwise, write directly to the stream.
         let mut partial: &[u8] = &[];
         super::write_with(stream, |stream| {
-            while total_len > 0 && !partial.is_empty() {
+            while total_len > 0 || !partial.is_empty() {
                 // If the partial buffer is non-empty, write it.
                 if !partial.is_empty() {
                     let n = stream.write(partial, fds)?;
```

**Comment by psychon** [comment]
Okay, I managed to convince myself that the above is correct by writing a test. See #811.

@serpilliere Thanks a lot for trying out x11rb-async and reporting problems!

> It seems that in the async version, the put_image request does not reach the x server.

Any request larger than 16384 was just silently dropped. So, xtrace is right. (And I couldn't believe it and first had to get wireshark involved before I really believed this :-D )

**Comment by serpilliere** [comment]
> Any request larger than 16384 bytes was just silently dropped. So, xtrace is right. (And I couldn't believe it and first had to get wireshark involved before I really believed this :-D )

Oh! I didn't know this.
I double checked this and it seems that xtrace logs data if I xtrace the original program (using the legacy x11rb).  The default image size is 100*100*4 (100x100 image, with 4 bytes per pixel) which gives 40000 bytes.
And I do have the message captured by xtrace:
```
server (7): Expose(ExposeEvent { response_type: 12, sequence: 7, window: 90177536, x: 0, y: 0, width: 100, height: 100, count: 0 })
client (8): PutImage(PutImageRequest { format: Z_PIXMAP, drawable: 90177536, gc: 90177537, width: 100, height: 100, dst_x: 0, dst_y: 0, left_pad: 0, depth: 24, data: [128, 128, 128, 128, 128, 128, 128, 128, 128,
128, 128, 128, 128, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 12
8, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128, 128, 128, 255, 128,
 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 1
28, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128
, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 12
8, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,...
```
I counted the buffer length, and it's more that 16384:
```python
>>> xx[:10]
[128, 128, 128, 128, 128, 128, 128, 128, 128, 128]
>>> len(xx)
40000
```
Did I miss something on the xtrace-example behavior?
Note to be sure we have the same setup: I use the xtrace-example from the x11rb example.

**Comment by psychon** [comment]
Uhm... I think you misunderstood me. Sorry!

There is a bug in x11rb-async that triggers when trying to send a request with more than 16384. My PR #811 fixes that bug.

At first I could not believe that there was such a bug. So I thought "there must be something wrong with xtrace!" and used wireshark to capture the data on the X11 connection. Only when Wireshark also did not show a PutImage request did I believe that there is such a bug in x11rb-async. And only then did I find the actual bug.

The bug is: Any request that is larger than 16384 bytes is not actually sent to the X11 server, but instead "forgotten" / "silently dropped" somewhere in x11rb-async.

**Comment by serpilliere** [comment]
Ok: I get it. I am trying the PR to check this here.

**Comment by serpilliere** [comment]
I tested the MP here, it works: it fixes the bug.
Thank you @psychon and @notgull  for your work!

Another point, bug more a question of design:
I read on the main x11rb README that you list some arguments "against" the async/await version and that if needed, we may do something wrong. So maybe I am doing something wrong, as it seems I need async in Sanzu:

To summary:
I am porting Sanzu to an async version (to decorrelate fps from network latency). And here is the problem:
Sanzu has one connection to the x server, in which the window is created. Sanzu must, at the same time:
- poll X events (keyboard, mouse, ...), then serialize and send those events to the server
- receive frames from the server and display them.

The polling of x events must be done really often, to avoid adding latency when reading the keyboard/mouse. So at best, Sanzu won't poll, but loop on a locking event read. But at anytime, we can have a frame from the server and so we must decode and set it to the x window (as quickly as possible, to avoid latency again). But if the connection is "locked" on a read from X events, we cannot get it to set the image.

We could have two connection, but I didn't miss something, I won't be able to manipulate a window handle created in a connection from the other (handles seem to be linked to the connections)

That's why, instead of pulling, Sanzu will use the async version.
From your point of view, is there something wrong in the design here so that we can fix design and keep using the legacy x11rb ?

**Comment by psychon** [comment]
> Sanzu has one connection to the x server, 

It actually has more than one. The crate you are using for clipboard handling creates another connection internally. ;-) 

> Sanzu must, at the same time:
> 
> - poll X events (keyboard, mouse, ...), then serialize and send those events to the server
> - receive frames from the server and display them.

How can you do those two things at the same time in async Rust? I guess you will have two tasks that each does one of these things and these two tasks run in parallel?

The sync version of that would be to have two threads that do those things in parallel. For example, Qt actually spawns a thread that calls `xcb_wait_for_event()` in a loop and forwards incoming events to their main loop.

I am actually not sure how to answer your question. There is https://docs.rs/x11rb/latest/x11rb/event_loop_integration/index.html, but you do not seem to have an "actual" event loop in sanzu. I ended up in `sanzu/src/server.rs`, function `run_server()` and that seems to just poll various sources and then sleep so that a certain FPS is achieved...

>  But if the connection is "locked" on a read from X events, we cannot get it to set the image.

Perhaps this is the crux of the problem. What do you mean with "locked"?

Both `RustConnection` and `XCBConnection` are `Sync`. That means you do not need to protect them with a `Mutex`. One thread can be in `wait_for_event()` waiting for an event while at the same time another thread can send a request. That works without problems.

For example, the [hypnomoire example](https://github.com/psychon/x11rb/blob/master/x11rb/examples/hypnomoire.rs) does... things with threads. This is a port to Rust of some C example. This creates three windows and each window has its own thread for redrawing the window. A fourth thread is waits for incoming events.

> We could have two connection, but I didn't miss something, I won't be able to manipulate a window handle created in a connection from the other (handles seem to be linked to the connections)

Nah. X11 is a free-for-all. That would actually work. But: Don't go that way. ;-)

**Comment by notgull** [comment]
I'd need to take a look at the code proper, but from your description, it sounds like your use case would be serviced using an [executor](https://docs.rs/async-executor/latest/async_executor/struct.LocalExecutor.html) running two tasks:

- One that polls events from the connection (an async connection, maybe) and then forwards those events to the server (if this is over a socket, it should be registered in an [`Async`](https://docs.rs/async-io/latest/async_io/struct.Async.html)).
- One that receives (reads on) events from the server and then uses that in a put image request on the connection.
- If image processing takes a while, you may want to [`unblock`](https://docs.rs/blocking/latest/blocking/fn.unblock.html) it.

**Comment by psychon** [comment]
>  Sanzu must, at the same time:
> 
> - poll X events (keyboard, mouse, ...), then serialize and send those events to the server
> - receive frames from the server and display them.

Actually... does it really have to do these at the same time? Looking at the code, the server is "actually doing work" and then at the end it sleeps (spinloops?) to achieve a certain FPS value: https://github.com/cea-sec/sanzu/blob/8ab83f0b50ad72adf43e7b24df013550c8dd1ffb/sanzu/src/server.rs#L568

Replacing this sleep with something like "wait for event with timeout" would make the main loop immediately wake up when "something X11" happens. An example for "wait for event with timeout" can be found here: https://github.com/psychon/x11rb/blob/3a283bf762eb9e2d875f29139c5ba9cdb363d1ec/x11rb/examples/xclock_utc.rs#L169-L208

This function sleeps until either
- the elapsed duration has elapsed (you might want to replace this `Duration` with an `Instant`... dunno)
- *or* some data is received from the X11 server

So... your current main loop (in pseudo code):
```
loop {
   do_other_stuff();
   while let Some(event) = conn.poll_for_event() {
       handle_event(event);
   }
   sleep(1. / 60.); // Sleep to achieve 60 FPs
}
```
What I am trying to propose here:
```
loop {
   do_other_stuff();

   let mut now = Instant::now();
   let sleep_until = Instant::now() + Duration::from_secs_f32(1.0 / 60.);
   while now < sleep_until {
       while let Some(event) = conn.poll_for_event() {
           handle_event(event);
       }
       poll_with_timeout(conn, sleep_until - now); // See link above for this function
       now = Instant::now();
   }
}
```
In theory, this could also integrate with other wakeup sources. I am not quite sure how messages from the client are received, but this could perhaps also be integrated into `poll`, but that would require some "plumbing" (right now you seem to be using unbuffered [UnixSockets](https://github.com/cea-sec/sanzu/blob/8ab83f0b50ad72adf43e7b24df013550c8dd1ffb/sanzu/src/server.rs#L154), [TCP sockets](https://github.com/cea-sec/sanzu/blob/8ab83f0b50ad72adf43e7b24df013550c8dd1ffb/sanzu/src/server.rs#L189), [stdio](https://github.com/cea-sec/sanzu/blob/8ab83f0b50ad72adf43e7b24df013550c8dd1ffb/sanzu/src/server.rs#L173) or whatever a [Vsock](https://github.com/cea-sec/sanzu/blob/8ab83f0b50ad72adf43e7b24df013550c8dd1ffb/sanzu/src/server.rs#L140) is (Google says this is something about a VM talking to its host / other VMs). I guess all of those should be integrateable with `poll()`, but that would be Linux-only.

**Comment by notgull** [comment]
Theoretically you should be using something like [`polling`](https://docs.rs/polling/latest/polling/) or [`mio`](https://docs.rs/mio/latest/mio/) instead of just the raw `poll()` syscall, especially since there's some subtlety involved with doing it on Windows. Although at that stage I'd just use `async`, since all contemporary async runtimes just use those crates under the hood, and it's generally easier/more extensible to put together than an event loop-oriented program.

**Comment by serpilliere** [comment]
@psychon :
> Nah. X11 is a free-for-all. That would actually work. But: Don't go that way. ;-)
Ok. The thing that make me say that is this:
```rust
    let (conn, screen_num) = x11rb::connect(None).expect("Failed to connect to the X11 server");
    let (conn2, screen_num2) = x11rb::connect(None).expect("Failed to connect to the X11 server");

    let screen = &conn.setup().roots[screen_num];

    let wm_protocols = conn.intern_atom(false, b"WM_PROTOCOLS").unwrap();
    let wm_delete_window = conn.intern_atom(false, b"WM_DELETE_WINDOW").unwrap();

    let window_size = (100, 100);
    let (wm_protocols, wm_delete_window) = (
        wm_protocols.reply().unwrap().atom,
        wm_delete_window.reply().unwrap().atom,
    );
    let win_id = setup_window(&conn, screen, window_size, wm_protocols, wm_delete_window).unwrap();


    // test
    let title = "xeyes toto";
    conn2.change_property8(
        PropMode::REPLACE,
        win_id,
        AtomEnum::WM_NAME,
        AtomEnum::STRING,
        title.as_bytes(),
    )
    .unwrap();
    conn2.flush().unwrap();
```
In this code, we have conn & conn2. And here, the window never renames to "xeyes toto". If I replace conn2 by conn in the `change_property`, the window is renamed. But maybe I missed something there

> Perhaps this is the crux of the problem. What do you mean with "locked"?

Sorry for not being clear here: I meant "sanzu will block on a wait_for_event". (not locked)

> Both RustConnection and XCBConnection are Sync. That means you do not need to protect them with a Mutex. One thread can be in wait_for_event() waiting for an event while at the same time another thread can send a request. That works without problems.

Thanks for the tip. 

>  Looking at the code, the server is "actually doing work"

Yes. But I am working on the client side.  The client needs to :
- handle x11 events (keyboard, mouse,...)
- handle video stream/sound received from the server

So in the side of sanzu, (which in mono thread in this version) we have a kind of loop like this:
![render](https://user-images.githubusercontent.com/9433661/230762425-aa5d5d9c-6aa0-498a-9eec-1c595190cb64.png)
So basically, we wait from a frame from the server, once received, we poll all X events during the last frame and now, and we send those events to the server.
Once the frame is decoded we want to display it, so calling pu_image
That's crappy, but that has some advantages and was the first version to validate every components. 
And this behavior is repeated for each frame. The interesting point here is that both client and server do their hard work at the same time and during the sent of data through the network.

In the 'async' version, we want to decorrelate frame reception from x11 events.  So that generates some 'concurrent' x11 calls:
- poll for events
- displaying frame.

Thank you for the example you provided.

For the vsock, yes: it is used in order communicate and display the screen of a virtual machine, even without network card.


@notgull : Yes! I started the async version because of this example, and that is exactly what I am testing :) Thank again for this async port

**Comment by psychon** [comment]
> In this code, we have conn & conn2. And here, the window never renames to "xeyes toto". If I replace conn2 by conn in the change_property, the window is renamed. But maybe I missed something there

Random guess: Race condition.

Just because you generate the `CreateWindow` request before the `ChangeProperty` request does not mean that the X11 server receives and handles these requests in the same order (and also `flush()` these requests in this order - your example didn't include a `conn.flush()` and this could also cause things to be sent "in the other order") . I bet that your example starts working if you [add a call to `conn.sync()`](https://docs.rs/x11rb/latest/x11rb/wrapper/trait.ConnectionExt.html#method.sync) before the `change_property` call.

What does `sync()` do? It just does `get_input_focus().reply()`. Since requests are sent in-order, this means that all previous requests were already sent. And by waiting for the reply, we know that the X11 server already handled the requests. Thus, the window really exists.

Races like these are the reason why I suggest not to use several X11 connections.

**Comment by serpilliere** [comment]
> Races like these are the reason why I suggest not to use several X11 connections.

Ah ok! Thank you for explanations @psychon !
With this answer, you killed two birds with one stone.
