### ISSUE TITLE
Improve ergonomics for "request name clashes"

### ISSUE THREAD

**Issue by psychon** [psychon/x11rb#82]
Both `xproto` and `shm` have a `CreatePixmap` request. Thus, I had to write this:
https://github.com/psychon/x11rb/blob/79c97a7d032a44e8602c9c47a2cbe892092a2f10/examples/shared_memory.rs#L38

I think it would be better if one could write
```rust
shm::create_pixmap(conn, other arguments here)?;
```
The idea here is to add back the API that commit 6ad7969701261f1e6a023d89187cd2ececba5627 removed. So, each request would be available in two places: as a module-level function and on the extension trait (and the function in the trait would just delegate to the module-level function).

**Comment by eduardosm** [comment]
What about adding a prefix to trait functions? We would have `conn.create_pixmap(...)` and `conn.shm_create_pixmap(...)`. For cases without name clashes, it would still help to quickly identify the extension of a request by looking at the method call.

For example, in randr there is `add_output_mode`, which has a unique name, but if someone sees `conn.add_output_mode(...)` might need some time to identify it as a randr request.

**Comment by psychon** [comment]
And `xproto` would get an empty prefix? Yeah, that sounds like a good idea.

(Also, what I proposed in this issue is long implemented. Too lazy to look up the exact commit right now.)

**Comment by eduardosm** [comment]
> And xproto would get an empty prefix? Yeah, that sounds like a good idea.

Exactly. I can work on it and send a PR unless you have started with it.

**Comment by psychon** [comment]
Feel free
