### ISSUE TITLE
Key grabbing issues for registering keybinds

### ISSUE THREAD

**Issue by mWalrus** [psychon/x11rb#828]
Opening this issue as requested in https://github.com/psychon/x11rb/issues/782.

Haven't had the time to keep hacking away at this issue since i wrote [my initial comment](https://github.com/psychon/x11rb/issues/782#issuecomment-1535986774) so the issue still stands.

I've pushed the code to a [keybinds branch](https://github.com/mWalrus/wwm/tree/keybinds) in my repo but running this is quite finicky because i haven't gotten around to streamlining that process yet.

To run you have to:
1. Have `Xephyr` and `xeyes` installed on your system
2. Run `Xephyr -screen 960x540 -ac -br :1` in one terminal
3. Stand in the project root directory in another terminal
4. Run `./run.sh`

This should launch the window manager along with 2 sessions of `xeyes` in the `Xephyr` window.

**Comment by psychon** [comment]
Something is wrong with the way you translate keysyms to keycodes. Or, rather, you do not do that at all.

dwm does (according to your quote in that other ticket):
```c
  syms = XGetKeyboardMapping(dpy, start, end - start + 1, &skip);
  if (!syms)
    return;
  for (k = start; k <= end; k++)
    for (i = 0; i < LENGTH(keys); i++)
      /* skip modifier codes, we do that ourselves */
      if (keys[i].keysym == syms[(k - start) * skip])
        for (j = 0; j < LENGTH(modifiers); j++)
          XGrabKey(dpy, k,
              keys[i].mod | modifiers[j],
              root, True,
              GrabModeAsync, GrabModeAsync);
```
This looks for `.keysym` of the key binding in the result of `XGetKeyboardMapping` and then uses the `k` computed that way for its call to `XGrabKey`.

Your code does not seem to do this translation. Instead, you directly use the keysym (e.g. `q`) as a keycode, even though the two are different. Running `xev` and pressing `q` says:
```
KeyPress event, serial 35, synthetic NO, window 0x3e00001,
    root 0x769, subw 0x0, time 1620358, (89,90), root:(2880,558),
    state 0x0, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (71) "q"
    XmbLookupString gives 1 bytes: (71) "q"
    XFilterEvent returns: False
```
So this is keycode 24 and keysym 0x71.

Running your WM under `xtrace` shows that the last `GrabKey` request that it sends is:
```
000:<:0083: 16: Request(33): GrabKey owner-events=true(0x01) grab-window=0x0000051e modifiers=Lock key=0x71 pointer-mode=Asynchronous(0x01) keyboard-mode=Asynchronous(0x01)
```
This has `key=0x71`. Dunno which key that would be on a keyboard.

How did I figure this out? Well... it took me way too long. In the end, I grabbed "everything" and got key events and only then did I notice that the contained numbers are off (again while using xtrace):
```rust
                conn.grab_key(
                    true,
                    screen.root,
                    x11rb::protocol::xproto::ModMask::ANY,
                    0,// keybind.keysym as u8,
                    GrabMode::ASYNC,
                    GrabMode::ASYNC,
                )?;
```
```
000:>:008e: Event KeyPress(2) keycode=0x18 time=0x001aba2d root=0x0000051e event=0x0000051e child=None(0x00000000) root-x=573 root-y=332 event-x=573 event-y=332 state=0 same-screen=true(0x01)
=========== got keypress
```
0x18 is 24 is the keycode for the key labeled `q`.

What's a keycode? It's a number for the physical key independent of the keyboard layout. No matter whether one uses a German or US keyboard layout, the key that is labeled either `y` or `z` has the same keycode.
