### ISSUE TITLE
Can someone please help me out and simulating a click?

### ISSUE THREAD

**Issue by candiedoperation** [psychon/x11rb#833]
I'm writing a RFB Server and I need to simulate pointer movement and clicks. I've tried using `warp_pointer()` and pointer movements work.  want to simulate a Mouse Click event, I've used `send_event()` and created a `ButtonPressEvent`. Did a lot of research but, Nothing Works! I'll paste my code here, Please help me out with this.

```
let query_pointer_cookie =
        xproto::query_pointer(&x11_server.connection, x11_screen.root.clone())
        .unwrap().reply().unwrap();

let x11_button_press_event: ButtonPressEvent = ButtonPressEvent {
        response_type: xproto::BUTTON_PRESS_EVENT, 
        detail: 1,
        sequence: 0,
        time: CURRENT_TIME,
        root: query_pointer_cookie.root,
        event: 1,
        child: query_pointer_cookie.child, 
        root_x: query_pointer_cookie.root_x, 
        root_y: query_pointer_cookie.root_y, 
        event_x: query_pointer_cookie.win_x, 
        event_y: query_pointer_cookie.win_y, 
        state: query_pointer_cookie.mask, 
        same_screen: query_pointer_cookie.same_screen 
 };

xproto::send_event(
      &x11_server.connection,
      true,
      query_pointer_cookie.root, /* XCB_SEND_EVENT_DEST_POINTER_WINDOW */
      EventMask::BUTTON_PRESS,
      x11_button_press_event,
).unwrap();
```

**Comment by psychon** [comment]
`SendEvent` really only does what you tell it to. You are sending the input event to the root window, so only the root window gets the event. You could send it to the currently focused window, but that is also not correct. X11 input processing is a bit involved: https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#events:input 

>  The event window is found by starting with the source window and looking up the hierarchy for the first window on which any client has selected interest in the event (provided no intervening window prohibits event generation by including the event type in its do-not-propagate-mask). The actual window used for reporting can be modified by active grabs and, in the case of keyboard events, can be modified by the focus window.

However, X11 provides a way to inject input events. It's the XTEST extension. Details can be found here: https://www.x.org/releases/X11R7.7/doc/xextproto/xtest.html, but the short version is: You only need this function: https://docs.rs/x11rb/0.11.1/x11rb/protocol/xtest/fn.fake_input.html

The "protocol" docs are sadly for the bindings from libX11 and not the actual protocol.

I don't have any examples for using the extension with x11rb, but here is some C code example:
https://github.com/awesomeWM/awesome/blob/6f000aad2a38a79d6c9b078df514ad6f2b58802f/root.c#L289-L343

This function is callable from Lua code. The arguments describe what kind of event his function should fake. Don't worry too much about the details. This should mostly demonstrate the possible cases and the corresponding arguments to the `FakeInput` request.

(The `globalconf.have_xtest` in that code comes from [here](https://github.com/awesomeWM/awesome/blob/6f000aad2a38a79d6c9b078df514ad6f2b58802f/awesome.c#L770-L773) and checks whether the xtest extension is available. With x11rb, you just need to check whether `conn.extension_information(x11rb::protocol::xtest::X11_EXTENSION_NAME)` is `None`).

**Comment by psychon** [comment]
Ohhh, also: You not only need to press the button, the button also needs to be released! That might actually be the problem with the example code you show.

**Comment by candiedoperation** [comment]
Whoops! I just came back after reading the XTEST extension. I implemented it and it works great. I read your response and you recommend it, it seems. Thank you so much for taking out time and answering my questions. Thanks a lot!
