### ISSUE TITLE
Fails to build for `powerpc-unknown-linux-gnu` with `dl-libxcb`

### ISSUE THREAD

**Issue by ids1024** [psychon/x11rb#834]
I wanted to test how something works on big endian, but it fails to build on architectures without 64-bit atomics:

```
# cross build --target powerpc-unknown-linux-gnu --features dl-libxcb
   Compiling x11rb v0.11.1 (/project/x11rb)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> x11rb/src/xcb_ffi/mod.rs:13:14
   |
13 |     atomic::{AtomicU64, Ordering},
   |              ^^^^^^^^^
   |              |
   |              no `AtomicU64` in `sync::atomic`
   |              help: a similar name exists in the module: `AtomicU8`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `x11rb` due to previous error
```

This presumably applies to other architectures that could run Rust std and X, but I'm not sure what. `i686-unknown-linux-gnu` seems to be fine.

This is simple enough, but annoying. A `Mutex<u64>` could work but be less performant (probably insignificantly). Looks like the `portable-atomic` crate is very widely used?

**Comment by notgull** [comment]
I opened #835 t close this.

> Looks like the `portable-atomic` crate is very widely used?

`portable-atomic` uses a spinloop on fallback, I wouldn't use it on `std` platforms.

**Comment by ids1024** [comment]
Ah yeah, if it uses spinlocks that's not generally desirable on std platforms.
