### ISSUE TITLE
`wait_for_event` without creating a window

### ISSUE THREAD

**Issue by voxxal** [psychon/x11rb#847]
I am trying to intercept all keystrokes, but don't want it to be limited to a single window. Would there be any way of intercepting all events with `wait_for_event`? Here is my current code for reference. `event happening` is never printed to the console.
```rs
println!("starting connection");
let (conn, screen_num) = connect(None).unwrap();
loop {
    println!("waiting for event");
    let next_event = conn.wait_for_event().unwrap();
    match next_event {
        _ => println!("event happening"),
	}
}
```

**Comment by notgull** [comment]
You probably want to use [`grab_keyboard`](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GrabKeyboard) before you start waiting for events.

**Comment by voxxal** [comment]
Got this issue resolved, thanks for all the help
