### ISSUE TITLE
WmHintsState::Withdrawn missing

### ISSUE THREAD

**Issue by daym** [psychon/x11rb#848]
See https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-hints.html

```
The definitions for the initial_state flag are:


#define	WithdrawnState	0
#define	NormalState	1	/* most applications start this way */
#define	IconicState	3	/* application wants to start as an icon */
```

**Comment by psychon** [comment]
Well, there is no WithdrawnState in ICCCM. From https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.4

> The value of the initial_state field determines the state the client wishes to be in at the time the top-level window is mapped from the Withdrawn state, as shown in the following table:

And then a table saying that NormalState has the value 1 and IconicState is 3.

A client wanting to be in withdrawn state when leaving the withdrawn state makes no sense to me.

Searching through ICCCM for `WithdrawnState` only finds the `WM_STATE` property where a `WithdrawnState` indeed exists and has value zero. But that's not `WmHintsState`.

Am I missing something?

**Comment by daym** [comment]
Huh, reading through that, I see what you mean.

What I'm trying to use that for is for creating a windowmaker dockapp (more specifically https://github.com/daym/wmpanel-rust/blob/ec884b3bb90e8b22c8e9e75d960b864311fd2e58/src/main.rs#L141 ).

I guess one can just set `initial_state = None` then?

**Comment by psychon** [comment]
> windowmaker dockapp

Huh, okay. Google and a bit searching through the repo indicates that this indeed sets `initial_state` to `WithdrawnState`: https://github.com/window-maker/dockapps/blob/f2bf4066c333a526d2f87733edb342acde7e466d/libdockapp/src/wmgeneral.c#L485

Soooo... next idea is "What does WindowMaker actually do?". Google and a bit of search through the repo (I searched for `StateHint`) found: https://github.com/window-maker/wmaker/blob/a52d13c8b8f807e1d25c2c0b1036d1de019b15d8/src/window.c#L752-L757

I guess this means that WindowMaker invented / abused ICCCM and added a new meaning to a pre-existing field that is not in the standard.

I would prefer not to explicitly support this kind of non-standard extension in x11rb. There are way too many private protocols and this would open an infinite can of worms. One can always construct the property value oneself.

Untested attempt (feel free to tell me if I should spend more time on this to produce something that actually works):
```rust
let mut hints = WmHints::new();
hints.initial_state = Some(WmHintsState::Iconic); // MISSING WithdrawnState
hints.icon_window = Some(iconwin_id);
hints.icon_position = Some((0, 0));
hints.window_group = Some(mainwin_id);
let mut hints = hints.serialize();
// Replace the above WmHintsState::Iconic with Withdrawn. This is a Window-Maker-specific non-standard protocol extension not explicitly supported by x11rb
hints[(2*4)..(3*4)].copy_from_slice(&0u32.to_ne_bytes());
conn.change_property(xproto::PropMode::REPLACE, mainwin_id, xproto::AtomEnum::WM_HINTS, xproto::AtomEnum::WM_HINTS, 32, 18, &hints);
```

**Comment by daym** [comment]
I agree that if windowmaker is doing weird non-standard protocols, x11rb shouldn't be made to accomodate every weird protocol there is.

Let's just drop the entire thing.

Thank you for your research.

**Comment by daym** [comment]
For completeness, even without your workaround and without WithdrawnState windowmaker 0.95.9 shows the dockapp as a dockapp just fine.

With your workaround I get this:

````
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `36`,
 right: `72`: `data` has an incorrect length', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/x11rb-protocol-0.12.0/src/protocol/xproto.rs:10166:9
````
