### ISSUE TITLE
How i can change size of font

### ISSUE THREAD

**Issue by PuffyWithEyes** [psychon/x11rb#873]
Hello, how I can change th size of font? I tried this code, but my text didn`t draw on the window:
```rust
let (conn, screen_num) = connect(None)?;
let screen = &conn.setup().roots[screen_num];
let gc = conn.generate_id()?;
let font = conn.generate_id()?;
conn.open_font(font, b"9x15")?;

let gc_aux = CreateGCAux::new()
    .graphics_exposures(0)
    .foreground(GREEN_COLOR)
    .font(font);

conn.create_gc(gc, screen.root, &gc_aux)?;
conn.close_font(font)?;

loop {
    conn.image_text8(window, gc, 100, 100, b"Hello World!")?;
}
```
but when i make simple text, it draws great:
```rust
let green_gc = create_gc_with_foreground(conn, window, GREEN_COLOR)?;

loop {
    conn.image_text8(window, green_font_gc.gcontext(), 100, 100, b"Hello World!")?;
}
``` 
Thank you very much in advance for your reply!

**Comment by psychon** [comment]
Does this example help you? https://github.com/psychon/x11rb/blob/2e9dbb534ea4cf0a42fc06f3b2ed35909dbf61c0/x11rb/examples/tutorial.rs#L1477-L1526

I ran it via `cargo run --example tutorial` and
```diff
diff --git a/x11rb/examples/tutorial.rs b/x11rb/examples/tutorial.rs
index 64e1d60..a99d837 100644
--- a/x11rb/examples/tutorial.rs
+++ b/x11rb/examples/tutorial.rs
@@ -2847,6 +2847,7 @@ fn example_visual_colormap_entries(visual: &Visualtype) -> u16 {
 }
 
 fn main() {
+    /*
     example1().unwrap();
     example2().unwrap();
     example3().unwrap();
@@ -2854,8 +2855,11 @@ fn main() {
     example5().unwrap();
     example6().unwrap();
     example7().unwrap();
+    */
     example8().unwrap();
+    /*
     example9().unwrap();
     example10().unwrap();
     example11().unwrap();
+    */
 }
```
-----
Some concrete thoughts on the code you show:

- Not a complete, runnable example, so I cannot experiment with it
- You should call `conn.flush()` or `conn.sync()` (from `x11rb::wrapper::ConnectionExt`) after calling `image_text8` to make sure the request doesn't just sit in the output buffer (`sync()` additionally sends a request to the X11 server and waits for the reply; that way it slows down the busy loop a bit)
- You could do `println!("{:?}", conn.poll_for_event());` in the loop. That would "show something" if your request causes an X11 error.
- Do you have a font named `9x15`? You can check with `/usr/bin/xlsfonts` (part of `x11-utils` on Debian) or the `list_fonts` example from `x11rb`. (for me, `xlsfonts` shows a font 9x15, but `list_fonts` does not; dunno why)

Also, a random warning: Core X11 fonts are state-of-the art from 1986. Don't expect anything modern from it.

**Comment by psychon** [comment]
https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:OpenFont doesn't say anything about possible errors from `OpenFont`, but the following:
```
Ok(Some(Error(X11Error { error_kind: Name, error_code: 15, sequence: 527, bad_value: 75497646, minor_opcode: 0, major_opcode: 45, extension_name: None, request_name: Some("OpenFont") })))
```
...sounds a lot like your `OpenFont` request fails with a `Name` error. Random guess: That means "no such font".

(`CreateGC` and `CloseFont` then fail due to `BadFont` since `OpenFont` failed and then `ImageText8` and `FreeGC` fail since the creation of the GC failed.)

**Comment by psychon** [comment]
> `$ fc-list | grep 9x15`

That's from `fontconfig` (gc). I don't think X11 fonts have anything to do with fontconfig (but I am not actually sure). That's why I suggested `xlsfonts`.

**Comment by PuffyWithEyes** [comment]
Yeah, in my system for some reason was not installed 9x15 font, but for example with "cursor" it work great
