### ISSUE TITLE
XChangeProperty equivalent for _XROOTPMAP_ID and ESETROOT_PMAP_ID

### ISSUE THREAD

**Issue by Swivelgames** [psychon/x11rb#882]
I'm trying to set the `_XROOTPMAP_ID` and `ESETROOT_PMAP_ID` Atoms on the Root Window, but it's not available in [x11rb::protocol::xproto::AtomEnum](https://docs.rs/x11rb/latest/x11rb/protocol/xproto/struct.AtomEnum.html)

```c
atom_root = XInternAtom(display, "_XROOTPMAP_ID", False);
atom_eroot = XInternAtom(display, "ESETROOT_PMAP_ID", False);

XChangeProperty(display, RootWindow(display, screen), atom_root, XA_PIXMAP, 32, PropModeReplace, (unsigned char *) &pixmap, 1);
XChangeProperty(display, RootWindow(display, screen), atom_eroot, XA_PIXMAP, 32, PropModeReplace, (unsigned char *) &pixmap, 1);
```

Any alternatives?

**Comment by psychon** [comment]
You are looking for the function `intern_atom`: https://docs.rs/x11rb/latest/x11rb/protocol/xproto/fn.intern_atom.html

Example: https://github.com/psychon/x11rb/blob/aca14e3cbacaa2a4f19fa5e6504f9005ef2d4f8d/x11rb/examples/tutorial.rs#L217

`AtomEnum` is the equivalent of stuff from `Xatom.h` like `XA_CUT_BUFFER0`. These are pre-defined atoms that always have the same value. Everything run-time goes through `XInternAtom` / `intern_atom`.

I am closing this ticket, but feel free to ask more questions here.

**Comment by Swivelgames** [comment]
Oh, good grief. Not sure how I missed that. Apologies for the frivolous issue! Thanks for the prompt and helpful reply!
