### ISSUE TITLE
Question: what is the state of x11rb-async?

### ISSUE THREAD

**Issue by Antikyth** [psychon/x11rb#900]
Hello, this is not a bug report, but rather a question (as the Discussion tab is not enabled for this repo, nor do I see any other places to ask questions linked). I've been trying to get an async wrapper around `rust-xcb` working in the past couple days, until I was made aware of `x11rb-async`. Looking into it, however, I can't find any information on its state - it has no mention in this repo's README.md, it does not have its own README.md in its directory, and it has no crate-level documentation.

Is `x11rb-async` ready to be used?

**Comment by notgull** [comment]
It depends.

It doesn't have a `libxcb` backend, as it would require a significant time and energy investment to get one working. So it makes it impractical to use in any application where a GPU is necessary. So it would only be useful in a pure-Rust application.

If you're fine with that caveat, it should be ready to be used. I wouldn't recommend using it in prod, but it shouldn't have any major bugs.

**Comment by psychon** [comment]
Well, x11rb-async does have [BlockingConnection](https://docs.rs/x11rb-async/latest/x11rb_async/blocking/struct.BlockingConnection.html) which can be used to wrap a XCBConnection from x11rb. But that is just "doing async" with a threadpool. It should work, but might not be the most performant option, but might be good enough. It does additionally have its own [RustConnection](https://docs.rs/x11rb-async/latest/x11rb_async/rust_connection/struct.RustConnection.html) which basically does the same thing as the RustConnection from x11rb, but in "proper async".

But yeah, I agree that x11rb-async should "just work".
