### ISSUE TITLE
#[repr(C)] Visualtype in xcb_ffi

### ISSUE THREAD

**Issue by Qelxiros** [psychon/x11rb#932]
This is necessary for functions like cairo's XCBSurface::create(). I'd be happy to submit a PR if this is a desired feature.

**Comment by notgull** [comment]
IIRC we're able to create `cairo` surfaces based on XCB without needing this type. See [here](https://github.com/psychon/x11rb/blob/master/cairo-example/src/main.rs) for an example. Could you expand on your use case?

**Comment by Qelxiros** [comment]
That example declares the type I'm describing. It's not a huge issue, and I have some bigger design issues I need to work out in the meantime, but it seems redundant for every application using cairo with x11rb to redefine this struct.

**Comment by psychon** [comment]
If you want XCB-compatible struct definitions, the usual way to get them in Rust is to use the XCB crate. See this specific line in the example: https://github.com/psychon/x11rb/blob/3e6b5eaae30d3c9e58235799c9a5b3e1d1d7e5a8/cairo-example/src/main.rs#L8

If we start annotating "random" structs with `#[repr(C)]`, where do we end? Why not having that annotation on all of them? Also, this opens a whole can of worms about this annotation actually being correct (the in-memory layout has to be the same and e.g. we leave out padding). I'd like to leave that can of worms closed.

> I'd be happy to submit a PR if this is a desired feature.

Do you actually have something done for this already? I'd be curious how you did this.
If not, do you know that most of the code here is auto-generated from an XML description of the X11 protocol? That makes this a bit more complicated. See https://github.com/psychon/x11rb/blob/master/doc/generated_code.md

**Comment by Qelxiros** [comment]
I would prefer not to depend on both xcb and x11rb, so defining my own struct works better. I wasn't proposing annotating the existing `Visualtype` with `#[repr(C)]`, rather creating a new struct (and potentially implementations to transform each into the other) in the `xcb_ffi` module, where it makes more sense (to me) to have a `#[repr(C)]` annotation. Regardless, your point about the XML generation is well-taken (I knew it was auto-generated, but I failed to consider how that might impact changes), and I can live with a slightly redundant struct definition. Thanks for your time!
